### ISSUE TITLE
WARNING: Command produced no valid data.

### ISSUE THREAD

**Issue by vamshimarati123** [tohojo/flent#101]
So let me explain my scenario. I am using Windows Azure RHEL73 VM and When i am running the command

 `flent tcp_upload -p totals -l 60 -H localhost -t text-to-be-included-in-plot -o filename1.png`
i am getting error like below 

> Started Flent 1.0.1-git-87a8f96 using Python 2.7.5.
> Starting tcp_upload test. Expected run time: 70 seconds.
> WARNING: Command produced no valid data.
> Runner class: NetperfDemoRunner
> Command: /bin/netperf -P 0 -v 0 -D -0.20 -6  -H localhost -p 12865 -t TCP_STREAM -l 60 -f m   --   -H localhost
> Return code: 0
> Stdout: Sorry, Demo Mode not configured into this netperf.
> Please consider reconfiguring netperf with
> --enable-demo=yes and recompiling
> 11281.49
> 
> Stderr:
> Data file written to ./tcp_upload-2017-03-23T112002.156585.text_to_be_included_in_plot.flent.gz.
> ERROR: Unable to plot -- matplotlib is missing! Please install it if you want plots.
so i downloaded the netperf and did --enable-demo=yes and also it's throwing same error. If any suggestions greatful and thanks in advance.

**Comment by dtaht** [comment]
It really looks like we tend to use much later versions of these tools and libs than are available in your os.

The two most common distros we use are ubuntu and arch.
