### ISSUE TITLE
ERROR: /usr/bin/netperf does not support demo mode

### ISSUE THREAD

**Issue by vamshimarati123** [tohojo/flent#102]
hi, so as of now i fed up with below error. I am using Windows Azure SLES12 SP2 vm .
`flent tcp_upload -p totals -l 60 -H localhost -t text-to-be-included-in-plot -o filename.png`

> Started Flent 1.0.1-git-87a8f96 using Python 2.7.13.
> Starting tcp_upload test. Expected run time: 70 seconds.
> ERROR: /usr/bin/netperf does not support demo mode.
if any suggestions helpful and thanks in advance.

**Comment by tohojo** [comment]
--enable-demo is a configuration switch when you compile netperf.

**Comment by vamshimarati123** [comment]
ok. so for that error i installed the netperf v2.6 rpm package from  ftp://ftp.pbone.net/mirror/ftp5.gwdg.de/pub/opensuse/repositories/home:/assmannst/RHEL_5/x86_64/netperf-2.6.0-9.1.x86_64.rpm
and it's working.
