### ISSUE TITLE
ERROR: Error loading PlotFormatter: KeyError

### ISSUE THREAD

**Issue by vamshimarati123** [tohojo/flent#103]
so i configured all the settings for FLENT and installed the pythin-matplotlib package `yum install python-matplotlib` it installed after that i ran `#./run-flent tcp_download -p totals -l 60 -H localhost -t text-to-be-included-in-plot -o filename.png` i got below error
```
Started Flent 1.0.1-git-87a8f96 using Python 2.7.5.
Starting rrul test. Expected run time: 70 seconds.
Data file written to ./rrul-2017-03-24T070822.774163.text_to_be_included_in_plot.flent.gz.
ERROR: Error loading PlotFormatter: KeyError(u'figure.max_open_warning is not a valid rc parameter.See rcParams.keys() for a list of valid parameters.',).
```
So  if any valuable suggestions appreciable and thanks in advance.....

**Comment by tohojo** [comment]
vamshimarati123 <notifications@github.com> writes:

> so i configured all the settings for FLENT and installed the pythin-matplotlib package yum install python-matplotlib it installed after that i ran #flent tcp_download -p totals
> -l 60 -H localhost -t text-to-be-included-in-plot -o filename.png i got below error
>
> Started Flent 1.0.1-git-87a8f96 using Python 2.7.5.
> Starting rrul test. Expected run time: 70 seconds.
> Data file written to ./rrul-2017-03-24T070822.774163.text_to_be_included_in_plot.flent.gz.
> ERROR: Error loading PlotFormatter: KeyError(u'figure.max_open_warning is not a valid rc parameter.See rcParams.keys() for a list of valid parameters.',).
>
> So if any valuable suggestions appreciable and thanks in advance.....

What's the output of `flent --version`?

-Toke

**Comment by Lupus** [comment]
Pip ships v1.0.1 which does not seem to have this change. I've applied the patch manually and the problem discussed disappeared for me.

```$ flent --version
Flent v1.0.1.
Running on Python 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)].
Using matplotlib version 1.2.0 on numpy 1.7.1.
```
