### ISSUE TITLE
ERROR: Unable to plot -- matplotlib is missing! Please install it if you want plots.

### ISSUE THREAD

**Issue by vamshimarati123** [tohojo/flent#104]
i am using SLES 12 SP2 VM in Microsoft Azure  and i configured all the settings and when i am executing the ```
#flent tcp_download -p totals -l 60 -H localhost -t text-to-be-included-in-plot -o filename.png
Started Flent 1.0.1-git-87a8f96 using Python 2.7.13.
Starting tcp_download test. Expected run time: 70 seconds.
Data file written to ./tcp_download-2017-03-24T070847.251803.text_to_be_included_in_plot.flent.gz.
ERROR: Unable to plot -- matplotlib is missing! Please install it if you want plots.
i searched a lot for the package in internet i could not able to find it so if any valuable suggestions appreciable and thanks in advance.....

**Comment by dtaht** [comment]
it's usually called python-matplotlib or py3-matplotlib or something like that.
