### ISSUE TITLE
VoIP rrul test

### ISSUE THREAD

**Issue by peteheist** [tohojo/flent#107]
Hi, I've been using the VoIP tests for a while, and already did a VoIP RRUL tests in the past, but for some reason now, while the standard 'voip' test is working, the 'voip_rrul' test is not. It may have been after I moved to using flent from source instead of the release build, but I'm not sure exactly. (I'm currently using D-ITG-2.8.1-r1023 and flent from the head).

I attached a tcpdump of ports 8000, 9000 and 9001 when running 'voip_rrul'. Can anyone tell what's wrong from this? It looks strange to me that the D-ITG server on port 9000 is responding with the byte 0x55 repeated 6 times, as that doesn't happen on a standard 'voip' test, that works.

[tcpdump_voip_rrul.txt](https://github.com/tohojo/flent/files/921729/tcpdump_voip_rrul.txt)

By the way, I start my control server with:

nohup python /usr/share/doc/flent/misc/ditg-control-server.py -a 0.0.0.0 --insecure-xml > ~/ditg-control-server.log 2>&1 &

**Comment by tohojo** [comment]
Pete Heist <notifications@github.com> writes:

> Hi, I've been using the VoIP tests for a while, and already did a VoIP
> RRUL tests in the past, but for some reason now, while the standard
> 'voip' test is working, the 'voip_rrul' test is not. It may have been
> after I moved to using flent from source instead of the release build,
> but I'm not sure exactly. (I'm currently using D-ITG-2.8.1-r1023 and
> flent from the head).
>
> I attached a tcpdump of ports 8000, 9000 and 9001 when running
> 'voip_rrul'. Can anyone tell what's wrong from this? It looks strange
> to me that the D-ITG server on port 9000 is responding with the byte
> 0x55 repeated 6 times, as that doesn't happen on a standard 'voip'
> test, that works.

It seems that the control server is successfully negotiating a
connection, but that DITG connection (on port 9000) fails. That's a TCP
RST response to the initial SYN, so it's most likely the kernel and not
D-ITG itself that sends it. Maybe the D-ITG server itself fails to
start, or crashes, or something?

-Toke

**Comment by peteheist** [comment]
You're right, thanks for noticing.

Fortunately (or unfortunately for sanity's sake) the problem seems to have disappeared after I made some "unrelated" network changes and rebooted the server, so it will have to remain unexplained for now. If it ever happens again I'll look into it more.
