### ISSUE TITLE
Custom app(tool) interation

### ISSUE THREAD

**Issue by Lupus** [tohojo/flent#108]
I'm currently experimenting with custom congestion control implementation for [udt](http://udt.sourceforge.net/) and flent seems like the tool for the job to test my custom load generating application in various scenarios on a small hardware test bed.

I did not find any examples on how custom application/tool can be integrated into flent along with the ones that are already supported. Should I just subclass `runners.ProcessRunner` like IperfCsvRunner does, import my module with runner in test config, and pass it as `command` somehow?

**Comment by Lupus** [comment]
After a bit more reading it seems that test code is invoked via `exec(compile(...))` inside the `TestEnvironment` class, so I can have some `.inc` module for my tests that monkey-patches the `TestEnvironment` and adds new finder commands for my custom app.

Is this the suggested/recommended/supported way to do this?

**Comment by tohojo** [comment]
"Konstantin A. Olkhovskiy" <notifications@github.com> writes:

> I did not find any examples on how custom application/tool can be
> integrated into flent along with the ones that are already supported.
> Should I just subclass runners.ProcessRunner like IperfCsvRunner does,
> import my module with runner in test config, and pass it as command
> somehow?

Yes, to add a new parser (which turns the tool output into a data
structure Flent can include in its results file), you just need to
subclass ProcessRunner and implement a suitable parse().

> After a bit more reading it seems that test code is invoked via
> exec(compile(...)) inside the TestEnvironment class, so I can have
> some .inc module for my tests that monkey-patches the TestEnvironment
> and adds new finder commands for my custom app.
>
> Is this the suggested/recommended/supported way to do this?

I would recommend against monkey-patching. Rather edit the
TestEnvironment class to add the method.

A finder method is not strictly necessary, though, if you're creating a
test for a custom tool that you know the invocation of, you can just set
the 'command' attribute in the test file to a string - that will then be
executed when the runner starts.

The purpose of the finder method is to disambiguate different commands
and do feature checking, and return an error to the user before the test
starts if something is wrong. Is the tool you are adding support for
generally available and useful outside your setting? If so, please feel
free to submit a pull request that adds the support; and in that case, a
runner is needed. :)

-Toke

**Comment by Lupus** [comment]
Hey @tohojo, thanks for quick reply!

> A finder method is not strictly necessary, though, if you're creating a
> test for a custom tool that you know the invocation of, you can just set
> the 'command' attribute in the test file to a string - that will then be
> executed when the runner starts.

Just a string with command line is lovely, thanks for the tip! But in order
to extract some data from the tool output I still would need a runner, is
that right?

> I would recommend against monkey-patching. Rather edit the
> TestEnvironment class to add the method.

I'd like to keep clean installation of flent and have my custom things
somewhere close to my custom app. Based on the above I would still
need a runner I presume, so can I use custom runner in a test, which
is imported from some other module?

> The purpose of the finder method is to disambiguate different commands
and do feature checking, and return an error to the user before the test
starts if something is wrong.

That makes sense.

> Is the tool you are adding support for generally available and useful outside
> your setting? If so, please feel free to submit a pull request that adds the support;
> and in that case, a runner is needed. :)

I'm working on a in-house tool specialized for certain setting that we happen to have.
So it's neither generally available, nor generally useful :)

**Comment by tohojo** [comment]
"Konstantin A. Olkhovskiy" <notifications@github.com> writes:

> Hey @tohojo, thanks for quick reply!
>
>  A finder method is not strictly necessary, though, if you're creating a
>  test for a custom tool that you know the invocation of, you can just set
>  the 'command' attribute in the test file to a string - that will then be
>  executed when the runner starts.
>
> Just a string with command line is lovely, thanks for the tip! But in order
> to extract some data from the tool output I still would need a runner, is
> that right?

Yup.

>  I would recommend against monkey-patching. Rather edit the
>  TestEnvironment class to add the method.
>
> I'd like to keep clean installation of flent and have my custom things
> somewhere close to my custom app. Based on the above I would still
> need a runner I presume, so can I use custom runner in a test, which
> is imported from some other module?

There's currently no support for this kind of plugin architecture, no,
but I'd accept a patch to add it. I think the easiest way would be to
use an environment variable that carries an extra module name to look
for runners in (e.g., FLENT_RUNNER_MODULE). It's quite simple to make
the get() method in runners.py look in that module if it can't find the
runner it is looking for...

The alternative is monkey-patching the flent.runners module, of course...

-Toke

**Comment by tohojo** [comment]
I'm closing this for now. Feel free to open a new bug for any specific functionality you need to support your usecase :)
