### ISSUE TITLE
ERROR: Error loading PlotFormatter: KeyError(u'figure.max_open_warning is not a valid rc parameter

### ISSUE THREAD

**Issue by sassmann** [tohojo/flent#111]
Trying to run the example from https://flent.org/intro.html I get the following error:

flent rrul -p all_scaled -l 60 -H 192.168.11.1 -o filename.png
Started Flent 1.0.1 using Python 2.7.5.
Starting rrul test. Expected run time: 70 seconds.
Data file written to ./rrul-2017-06-08T055423.229029.flent.gz.
ERROR: Error loading PlotFormatter: KeyError(u'figure.max_open_warning is not a valid rc parameter.See rcParams.keys() for a list of valid parameters.',).

Might be that matplotlib is too old python-matplotlib-1.2.0-15.el7.x86_64, running this on RHEL7.

**Comment by tohojo** [comment]
sassmann <notifications@github.com> writes:

> Trying to run the example from https://flent.org/intro.html I get the following error:
>
> flent rrul -p all_scaled -l 60 -H 192.168.11.1 -o filename.png
> Started Flent 1.0.1 using Python 2.7.5.
> Starting rrul test. Expected run time: 70 seconds.
> Data file written to ./rrul-2017-06-08T055423.229029.flent.gz.
> ERROR: Error loading PlotFormatter: KeyError(u'figure.max_open_warning is not a valid rc parameter.See rcParams.keys() for a list of valid parameters.',).
>
> Might be that matplotlib is too old
> python-matplotlib-1.2.0-15.el7.x86_64, running this on RHEL7.

Yeah, this is an error with old matplotlib versions. Pretty sure it's
already fixed in git, could you try the latest git version and see if
the problem persists? :)

-Toke

**Comment by sassmann** [comment]
The latest git version works fine.
Thanks Toke!

**Comment by tohojo** [comment]
sassmann <notifications@github.com> writes:

> The latest git version works fine.
> Thanks Toke!

Awesome! You're welcome :)

-Toke
