### ISSUE TITLE
flent gui - graphing improvements

### ISSUE THREAD

**Issue by eriktar** [tohojo/flent#113]
I'd like to have a "zoom out" button/keyboard shortcut.  And a button for "scale the Y axes to include 0".  

Why scale?
I have noticed that when I'm demonstrating graphing with this tool, few notice the scale.  So when swapping between two tabs with different results, given the default zoom-in-to-the-interesting-bits it can go unnoticed that there can be quite a jump as to what it starts plotting on the Y.  Perhaps even "use this scale on all tabs" feature.

Why zoom out?
When creating the perfect zoom level for a screen shot I tend to zoom a bit to far in.  The ability to go a little back in stead of starting at "home" zoom would be nice.

I know these are nitpick level issues, but still they would improve my workflow.

**Comment by tohojo** [comment]
eriktar <notifications@github.com> writes:

> I'd like to have a "zoom out" button/keyboard shortcut.  And a button for "scale the Y axes to include 0".  
>
> Why scale?
> I have noticed that when I'm demonstrating graphing with
> this tool, few notice the scale. So when swapping between two tabs
> with different results, given the default
> zoom-in-to-the-interesting-bits it can go unnoticed that there can be
> quite a jump as to what it starts plotting on the Y. Perhaps even "use
> this scale on all tabs" feature.

Yeah, differently scaled plots can be a gotcha. There's already some
support for remedying this: You can enable 'scale mode', which will load
additional data sets that are not plotted but instead used to calculate
the axis bounds. The idea is that you load all your data files into each
plot, and they will then have the same scale.

You can enable scale mode in the GUI in the settings menu, then add
extra data plots for scale data using the 'open files' selector. There's
also a shortcut to load all open data sets into all tabs; that's the
"Scale open data files" option in the Data menu.

The 'set Y axis to zero' option is also already present on the command
line, but it is not exposed in the GUI. However, you can pass options
when starting the GUI (i.e., run `flent-gui --zero-y`) and it will be
used for all plots. I have plans to expose all the plotting options in
the GUI, but have not gotten around to coding it up yet.

Finally, the matplotlib plot widget has an option to edit axis
parameters that you can use to explicitly set bounds on the axes. One of
the buttons on the toolbar next to the plot should open this option.

> Why zoom out?
> When creating the perfect zoom level for a screen shot I tend to zoom
> a bit to far in.  The ability to go a little back in stead of starting
> at "home" zoom would be nice.

Yeah, that has annoyed me as well. You can zoom out by drawing the zoom
rectangle with the right mouse button. The feature is a bit annoying to
use, but can be used to do what you want. Having a zoom shortcut is not
a bad idea, though (mouse wheel perhaps)?

Also, for creating publication-quality plots I can recommend using the
command line; there are a lot of options that give you detailed control
over many aspects of the plot. As I mentioned above, I plan to expose
these in the GUI as well, but until I get around to that, you can use
them from the command line.

-Toke

**Comment by eriktar** [comment]
On Wed, Sep 6, 2017 at 2:40 PM, Toke Høiland-Jørgensen <
notifications@github.com> wrote:

> The 'set Y axis to zero' option is also already present on the command
> line, but it is not exposed in the GUI. However, you can pass options
> when starting the GUI (i.e., run `flent-gui --zero-y`) and it will be
> used for all plots. I have plans to expose all the plotting options in
> the GUI, but have not gotten around to coding it up yet.
>

Actually, you have implemented this in the GUI I found out digging around
now. My bad for being a bit to lazy.  :)  Settings --> Zero Y-Axis



> Finally, the matplotlib plot widget has an option to edit axis
> parameters that you can use to explicitly set bounds on the axes. One of
> the buttons on the toolbar next to the plot should open this option.
>

I have found this, but for "every day" use I find it a bit to may steps to
work comfortably in my workflow.  Very useful when building proper reports
etc.



> Yeah, that has annoyed me as well. You can zoom out by drawing the zoom
> rectangle with the right mouse button. The feature is a bit annoying to
> use, but can be used to do what you want. Having a zoom shortcut is not
> a bad idea, though (mouse wheel perhaps)?
>

If you do add the keyboard shortcuts, please reuse the once from
wireshark.  Upper/lower case x and y for the different axes.



> Also, for creating publication-quality plots I can recommend using the
> command line; there are a lot of options that give you detailed control
> over many aspects of the plot. As I mentioned above, I plan to expose
> these in the GUI as well, but until I get around to that, you can use
> them from the command line.
>

I started in that mode.  CLI only.  But for the more non-formal reporting
such as email attachments etc, grabbing the screen is very convenient  to
keep up the flow.

-Erik

**Comment by tohojo** [comment]
eriktar <notifications@github.com> writes:

> On Wed, Sep 6, 2017 at 2:40 PM, Toke Høiland-Jørgensen <
> notifications@github.com> wrote:
>
>> The 'set Y axis to zero' option is also already present on the command
>> line, but it is not exposed in the GUI. However, you can pass options
>> when starting the GUI (i.e., run `flent-gui --zero-y`) and it will be
>> used for all plots. I have plans to expose all the plotting options in
>> the GUI, but have not gotten around to coding it up yet.
>>
>
> Actually, you have implemented this in the GUI I found out digging around
> now. My bad for being a bit to lazy.  :)  Settings --> Zero Y-Axis

Ah yes, so I did. Cool ;)

>> Finally, the matplotlib plot widget has an option to edit axis
>> parameters that you can use to explicitly set bounds on the axes. One of
>> the buttons on the toolbar next to the plot should open this option.
>>
>
> I have found this, but for "every day" use I find it a bit to may steps to
> work comfortably in my workflow.  Very useful when building proper reports
> etc.

Yeah, I agree. The Flent-specific options should be exposed in the GUI.

>> Yeah, that has annoyed me as well. You can zoom out by drawing the zoom
>> rectangle with the right mouse button. The feature is a bit annoying to
>> use, but can be used to do what you want. Having a zoom shortcut is not
>> a bad idea, though (mouse wheel perhaps)?
>>
>
> If you do add the keyboard shortcuts, please reuse the once from
> wireshark.  Upper/lower case x and y for the different axes.

Noted.

>> Also, for creating publication-quality plots I can recommend using the
>> command line; there are a lot of options that give you detailed control
>> over many aspects of the plot. As I mentioned above, I plan to expose
>> these in the GUI as well, but until I get around to that, you can use
>> them from the command line.
>>
>
> I started in that mode.  CLI only.  But for the more non-formal reporting
> such as email attachments etc, grabbing the screen is very convenient  to
> keep up the flow.

True. Ideally, I think the 'save' command in the GUI should save
whatever plot is currently shown, optionally with some rescaling. Not
sure to what extent this is possible (for saving PDFs the plots need to
be redrawn, for instance), but I'll look into that :)

-Toke
