### ISSUE TITLE
[Feature Request] Add a flag to internally use iperf instead of netperf

### ISSUE THREAD

**Issue by q2dg** [tohojo/flent#115]
I haven't found it on help. And in https://flent.org/intro.html#quick-start there's no mention to use iperf instead of netperf/netserver
Thanks!

**Comment by tohojo** [comment]
Iperf and netperf are not feature compatible, so that's not straight forward. Why do you want to use iperf (I assume you mean for the TCP tests here, right?)?

**Comment by q2dg** [comment]
Yes. Because it seems much more maintained....at least seeing its commit activity. But if you consider it isn't worthy, it's fine. Thanks.

**Comment by dtaht** [comment]
Osqui LittleRiver <notifications@github.com> writes:

> Yes. Because it seems much more maintained....at least seeing its commit
> activity. But if you consider it isn't worthy, it's fine. Thanks.

iperf has many flaws being corrected, so you might view the commit
activity as a reflection of that. :)

netperf, on the other hand, has been stable for a very long time, its
flaws are well understood, and as such it is generally the preferred
test driver of the linux kernel community.

I do hope one day to have faith in iperf's results.

**Comment by q2dg** [comment]
Ok. However, I'm wondering which tool is used in Fedora/CentOS community, then (netperf isn't packaged in these systems)

Feel free to close this issue if you consider it's better.
Thanks
