### ISSUE TITLE
tcp_rtt plot doesn't seem to work with rrul_be_nflows

### ISSUE THREAD

**Issue by peteheist** [tohojo/flent#116]
Hi, just noticed that when I run these commands there's no data plotted in the resulting plot title_tcp_rtt.png (copying from a script so this is just a rough idea of what I'm doing):

```
flent rrul_be_nflows -l 60 -H 10.9.0.2 -p all_scaled \
	--figure-width=10 --figure-height=7.5 \
	--socket-stats \
	--test-parameter upload_streams=4 \
	--test-parameter download_streams=4 \
	-t title -o title.png

flent -p tcp_rtt -i *.flent.gz -o title_tcp_rtt.png
```

I just pulled this from the head to make sure. If I run an `rrul_be` test instead, the `tcp_rtt` plot does contain data as expected, so it seems like it's something with `rrul_be_nflows` that happens during plot generation. I can see `tcp_rtt` values in the .flent.gz file.

**Comment by tohojo** [comment]
Pete Heist <notifications@github.com> writes:

> Hi, just noticed that when I run these commands there's no data plotted in the resulting plot title_tcp_rtt.png (copying from a script so this is just a rough idea of what I'm doing):
>
> ```
> flent rrul_be_nflows -l 60 -H 10.9.0.2 -p all_scaled \
> 	--figure-width=10 --figure-height=7.5 \
> 	--socket-stats \
> 	--test-parameter upload_streams=4 \
> 	--test-parameter download_streams=4 \
> 	-t title -o title.png
>
> flent -p tcp_rtt -i *.flent.gz -o title_tcp_rtt.png
> ```
>
> I just pulled this from the head to make sure. If I run an `rrul_be`
> test instead, the `tcp_rtt` plot does contain data as expected, so it
> seems like it's something with `rrul_be_nflows` that happens during
> plot generation. I can see `tcp_rtt` values in the .flent.gz file.

Could you attach the data file, please? Then I'll have a look :)

-Toke

**Comment by peteheist** [comment]
Surely, that would've been a good idea...

[rrul_be_nflows-2017-11-15T174330.290403.nolimit_4flows_4cores.flent.gz](https://github.com/tohojo/flent/files/1475551/rrul_be_nflows-2017-11-15T174330.290403.nolimit_4flows_4cores.flent.gz)

**Comment by peteheist** [comment]
Great, that fixes it for me, thanks...
