### ISSUE TITLE
saving plots in the data dir rather than the root

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#12]
in the general case I like to keep the plots I make in the data directory itself, and to retain whatever directory I last saved in for future plots.

Saving in the home dir is a PITA.

**Comment by tohojo** [comment]
This is definitely on the list for "be easier to use out of the box"...

**Comment by tohojo** [comment]
Related to #28.

**Comment by dtaht** [comment]
no, this is more surprising than the behavior I requested - that the *gui* put the plot output in the started from directory. The default for the data output should be the local dir, unless overridden by -D whatever.

**Comment by tohojo** [comment]
Whaddya mean? The GUI doesn't output anything without popping up a file dialog...

**Comment by dtaht** [comment]
the gui file dialog defaults to $HOME. And stays there even after you save the first file somewhere else. It should default to the starting dir for the initial command, and retain the previous location it saved to on further saves.

**Comment by dtaht** [comment]
I stand half corrected. It retains the previous location it saved to on further saves. still defaults to $HOME at start. 

AND - fiddling with it - it does not retain the previous graph output format on further saves. (I prefer .svg for most stuff)

It would be nice to set the preferred graph output format in the rc file (haven't looked) and to retain the output format from save to save.

**Comment by tohojo** [comment]
Both the default save dir and default file format can be set through
matplotlibrc. The keys are `savefig.directory` and `savefig.format`
respectively.

It seems that `savefig.directory` defaults to '~' - but I'm not sure
overriding it from the GUI is a good idea; that would prevent people
from actually setting it. Also, what would it default to?
