### ISSUE TITLE
UDP averages seem off in batch output

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#120]
I would prefer to think it was flent that was busted here rather than cake.

Summary of rrul_be test run '100-10Mbit:nat:ack_filter' (at 2017-11-22 22:17:58.800917):
                              avg       median          # data pts
 Ping (ms) ICMP    :         0.86         0.88 ms              351
 Ping (ms) UDP BE1 :      1006.76         1.85 ms              350 ?
 Ping (ms) UDP BE2 :      1003.68         1.85 ms              350 ?
 Ping (ms) UDP BE3 :      1099.73         1.74 ms              350 ?
 Ping (ms) avg     :      1036.72         1.56 ms              351
 TCP download BE   :         1.96         1.96 Mbits/s         301
 TCP download BE2  :         1.96         1.96 Mbits/s         300
 TCP download BE3  :         1.96         1.96 Mbits/s         301
 TCP download BE4  :         1.96         1.96 Mbits/s         301
 TCP download avg  :         1.96         1.97 Mbits/s         301
 TCP download sum  :         7.84         7.86 Mbits/s         301
 TCP totals        :        64.32        64.28 Mbits/s         301
 TCP upload BE     :        14.12        14.09 Mbits/s         301
 TCP upload BE2    :        14.12        14.09 Mbits/s         300
 TCP upload BE3    :        14.12        14.16 Mbits/s         301
 TCP upload BE4    :        14.12        14.13 Mbits/s         301
 TCP upload avg    :        14.12        14.12 Mbits/s         301
 TCP upload sum    :        56.48        56.48 Mbits/s         301

**Comment by tohojo** [comment]
Data file and debug log would be useful...
