### ISSUE TITLE
correct use of udp_flood_var_up?

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#121]
flent -H 172.22.148.9 -H 172.22.148.9 -H 172.22.148.9 -H 172.22.148.9 -t cake-simul udp_flood_var_up

?
[udp_flood_var_up-2017-11-23T154421.462961.cake-simul.flent.gz](https://github.com/tohojo/flent/files/1500331/udp_flood_var_up-2017-11-23T154421.462961.cake-simul.flent.gz)

**Comment by tohojo** [comment]
Dave Täht <notifications@github.com> writes:

> flent -H 172.22.148.9 -H 172.22.148.9 -H 172.22.148.9 -H 172.22.148.9
> -t cake-simul udp_flood_var_up

You can't repeat the same host. If you want more data to the same host
use --test-parameter udp_bandwidth=400M
