### ISSUE TITLE
irtt not used for rrul_be_nflows

### ISSUE THREAD

**Issue by peteheist** [tohojo/flent#123]
Actually not sure if this should work yet or not, but rrul_be_nflows is one of the more common tests I do and it still uses UDP_RR...

**Comment by tohojo** [comment]
Pete Heist <notifications@github.com> writes:

> Actually not sure if this should work yet or not, but rrul_be_nflows
> is one of the more common tests I do and it still uses UDP_RR...

Hmm, the test has been converted, so it's probably due to the fallback
behaviour. If you run Flent in verbose mode (-v) the debug output should
tell you whether the irtt suitability check fails...

**Comment by peteheist** [comment]
Duh, I didn't have an up to date irtt in my test bed. `-v` was helpful, thanks.

Maybe I need to set up my test bed to update irtt on commit.
