### ISSUE TITLE
occasional WARNING: Unable to get packet timestamp and seqno 

### ISSUE THREAD

**Issue by peteheist** [tohojo/flent#124]
I'm filing this here for the moment but we can move it to irtt if it turns out to be something for me. The warning says:

Unable to get packet timestamp and seqno: u'wall'

The seqno does some to be there though.

It seems to happen when `lost` is `true_down`, which would mean there aren't any server timestamps or client receive timestamps. Maybe it's just from expecting timestamps that aren't there for lost packets?

```
{u'delay': {}, u'seqno': 32, u'ipdv': {}, u'lost': u'true_down', u'timestamps': {u'client': {u'receive': {}, u'send': {u'wall': 1511592021974184048, u'monotonic': 6404567840}}, u'server': {u'receive': {}, u'send': {}}}}
WARNING: Unable to get packet timestamp and seqno: u'wall'
{u'delay': {}, u'seqno': 100, u'ipdv': {}, u'lost': u'true_down', u'timestamps': {u'client': {u'receive': {}, u'send': {u'wall': 1511592035774087212, u'monotonic': 20204471098}}, u'server': {u'receive': {}, u'send': {}}}}
WARNING: Unable to get packet timestamp and seqno: u'wall'
{u'delay': {}, u'seqno': 147, u'ipdv': {}, u'lost': u'true_down', u'timestamps': {u'client': {u'receive': {}, u'send': {u'wall': 1511592045174099939, u'monotonic': 29604483791}}, u'server': {u'receive': {}, u'send': {}}}}
```

**Comment by peteheist** [comment]
By the way, in case you'd want undocumented flags for both client and server for dropping or duplicating some percentage of packets I can add that. I currently have compiled in constants for those.

**Comment by tohojo** [comment]
This is already fixed, you just need to pull the latest version...

**Comment by peteheist** [comment]
Yep, that fixed it (three runs an no warning), thanks!
