### ISSUE TITLE
capturing DUMP_TCP_INFO stats when possible would be nice

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#13]
Each TCP flow on later versions of netperf can dump it's tcp statistics which seems useful information to collect.

d@nuc-client:~/git/netperf$ DUMP_TCP_INFO=1 netperf -H ranger
MIGRATED TCP STREAM TEST from ::0 (::) port 0 AF_INET6 to ranger () port 0 AF_INET6 : demo
tcpi_rto 204000 tcpi_ato 0 tcpi_pmtu 1500 tcpi_rcv_ssthresh 28800
tcpi_rtt 3482 tcpi_rttvar 455 tcpi_snd_ssthresh 91 tpci_snd_cwnd 105
tcpi_reordering 3 tcpi_total_retrans 9
Recv   Send    Send  
Socket Socket  Message  Elapsed  
Size   Size    Size     Time     Throughput  
bytes  bytes   bytes    secs.    10^6bits/sec  

 87380  16384  16384    10.04     294.61   

d@nuc-client:~/git/netperf$ DUMP_TCP_INFO=1 netperf -H snapon.lab.bufferbloat.net
MIGRATED TCP STREAM TEST from ::0 (::) port 0 AF_INET6 to snapon.lab.bufferbloat.net () port 0 AF_INET6 : demo
tcpi_rto 224000 tcpi_ato 0 tcpi_pmtu 1500 tcpi_rcv_ssthresh 28800
tcpi_rtt 23011 tcpi_rttvar 1872 tcpi_snd_ssthresh 7 tpci_snd_cwnd 9
tcpi_reordering 3 tcpi_total_retrans 2
Recv   Send    Send  
Socket Socket  Message  Elapsed  
Size   Size    Size     Time     Throughput  
bytes  bytes   bytes    secs.    10^6bits/sec  

 87380  16384  16384    10.42       5.29  
d@nuc-client:~/git/netperf$

**Comment by tohojo** [comment]
On 3 April 2015 03:33:18 CEST, "Dave Täht" <notifications@github.com> wrote:
> Each TCP flow on later versions of netperf can dump it's tcp
> statistics which seems useful information to collect.
> 
> d@nuc-client:~/git/netperf$ DUMP_TCP_INFO=1 netperf -H ranger
> MIGRATED TCP STREAM TEST from ::0 (::) port 0 AF_INET6 to ranger ()
> port 0 AF_INET6 : demo
> tcpi_rto 204000 tcpi_ato 0 tcpi_pmtu 1500 tcpi_rcv_ssthresh 28800
> tcpi_rtt 3482 tcpi_rttvar 455 tcpi_snd_ssthresh 91 tpci_snd_cwnd 105
> tcpi_reordering 3 tcpi_total_retrans 9
> Recv   Send    Send                          
> Socket Socket  Message  Elapsed              
> Size   Size    Size     Time     Throughput  
> bytes  bytes   bytes    secs.    10^6bits/sec  
> 
>  87380  16384  16384    10.04     294.61   
> 
> d@nuc-client:~/git/netperf$ DUMP_TCP_INFO=1 netperf -H
> snapon.lab.bufferbloat.net
> MIGRATED TCP STREAM TEST from ::0 (::) port 0 AF_INET6 to
> snapon.lab.bufferbloat.net () port 0 AF_INET6 : demo
> tcpi_rto 224000 tcpi_ato 0 tcpi_pmtu 1500 tcpi_rcv_ssthresh 28800
> tcpi_rtt 23011 tcpi_rttvar 1872 tcpi_snd_ssthresh 7 tpci_snd_cwnd 9
> tcpi_reordering 3 tcpi_total_retrans 2
> Recv   Send    Send                          
> Socket Socket  Message  Elapsed              
> Size   Size    Size     Time     Throughput  
> bytes  bytes   bytes    secs.    10^6bits/sec  
> 
>  87380  16384  16384    10.42       5.29   
> d@nuc-client:~/git/netperf$ 
> 
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/tohojo/netperf-wrapper/issues/13

Noted. This is a feature of svn netperf?

**Comment by dtaht** [comment]
yes. I am hoping rick freezes a 2.7 release with this and the udplite stuff.
