### ISSUE TITLE
Tests not Completing When Ran in Windows 10 Ubuntu Subsystem

### ISSUE THREAD

**Issue by Jonatino** [tohojo/flent#130]
Setup flent in my Ubuntu subsystem for Windows 10 using Xming server to show the GUI.

When I run the built-in tests they never complete (image below has been stuck at 100% for 20 minutes). Is there any additional logging I can turn on to try and figure this out?

![img](https://i.imgur.com/uDY4S2D.png)

**Comment by tohojo** [comment]
Jonathan Beaudoin <notifications@github.com> writes:

> Setup flent in my Ubuntu subsystem for Windows 10 using Xming server to show the GUI.
>
> When I run the built-in tests they never complete (image below has
> been stuck at 100% for 20 minutes). Is there any additional logging I
> can turn on to try and figure this out?

Hmm, could you try running the test from the command line and enabling
logging?

flent -v -L debug.log rrul_be <hostname>

and see if (a) that works and (b) if not, post the log somewhere?

-Toke

**Comment by Jonatino** [comment]
@tohojo 

Unfortunately, command line did not work either. Ran the test and left it for 30 minutes, here is the output from the log file.

`
2018-03-23 13:43:23,151 [flent.settings] DEBUG: Executing test environment file /usr/share/flent/flent/tests/rrul_be.conf
2018-03-23 13:43:23,159 [flent.settings] INFO: Started Flent 1.2.0 using Python 3.5.2.
2018-03-23 13:43:23,163 [flent.settings] DEBUG: Executing test environment file /usr/share/flent/flent/tests/rrul_be.conf
`

https://dl.dropboxusercontent.com/s/l1uwdncftanogh2/debug.log

**Comment by tohojo** [comment]
Jonathan Beaudoin <notifications@github.com> writes:

> @tohojo 
>
> Unfortunately, command line did not work either. Ran the test and left it for 30 minutes, here is the output from the log file.
>
> `
> 2018-03-23 13:43:23,151 [flent.settings] DEBUG: Executing test environment file /usr/share/flent/flent/tests/rrul_be.conf
> 2018-03-23 13:43:23,159 [flent.settings] INFO: Started Flent 1.2.0 using Python 3.5.2.
> 2018-03-23 13:43:23,163 [flent.settings] DEBUG: Executing test
> environment file /usr/share/flent/flent/tests/rrul_be.conf

Wait, this is the *only* output you see? This is decidedly odd. Could
you run flent under strace to see why it stops?

-Toke

**Comment by Jonatino** [comment]
@tohojo 

[strace.txt](https://github.com/tohojo/flent/files/1843863/strace.txt)

**Comment by tohojo** [comment]
Okay, this is decidedly weird. From the strace output it looks like Flent is writing more stuff to stderr, but it never appears anywhere. But there is also definitely log output missing; looks like only the log lines from the settings module are actually output.

I think I have a windows 10 VM lying around somewhere, so I'll see if I can replicate this. Did you install Flent from the PPA?

**Comment by tohojo** [comment]
There is definitely a risk that it is not something that can easily be worked around in flent. But it is still really odd behaviour...

**Comment by tohojo** [comment]
OK, so tried this on win10 and could not reproduce the behaviour you are seeing.

The ping binary doesn't work properly on win10, though; could you try to see what happens if you run the tcp_1up_noping test?

**Comment by Jonatino** [comment]
@tohojo were you using the Ubuntu subsystem? Now that I think about it, it could totally be that my subsystem is using the wrong NIC by default (I have multiple NICs in my computer).

I will check again when I get home.

**Comment by tohojo** [comment]
It just occurred to me that the issue might be a hanging hostname lookup. I've added a debug statement before looking up hostnames, so if you could try running the git version with -v, it should be pretty clear if this is what is happening...

**Comment by Jonatino** [comment]
@tohojo no luck. The following is the output of hostnames[0]

```
Executing test environment file /home/jonathan/flent/flent/tests/rrul_be.conf
Looking up hostname1234 '107.191.96.000', '4'.
Found hostname '(2, 1, 6, '', ('107.191.96.000', 0))'.
```

Which matches the output on my working VirtualBox ubuntu.


Going to continue walking through the code and see why it's not started.

**Comment by Jonatino** [comment]
@tohojo this seems to be an issue with the subsystem in windows.

https://github.com/Microsoft/WSL/issues/2026

thanks for your help.

**Comment by tohojo** [comment]
Jonathan Beaudoin <notifications@github.com> writes:

> @tohojo this seems to be an issue with the subsystem in windows.
>
> https://github.com/Microsoft/WSL/issues/2026
>
> thanks for your help.

Ah, right, nice catch. Might be worth dealing with the case where the
metadata gathering commands hang. I'll look into that :)

-Toke
