### ISSUE TITLE
Couldn't resolve host name' while getting URL list at http://%s/filelist.txt

### ISSUE THREAD

**Issue by teto** [tohojo/flent#137]
I wonder if there isn't an error at 
https://github.com/tohojo/flent/blob/710f9f253944668b3d4200e1e3aa90cecba954db/flent/runners.py#L1251
like it should be 
```
                    or "http://{}/filelist.txt".format(self.settings.HOST))
```
else in the log I get
```
2018-06-07 09:10:48,860 [flent.runners] DEBUG: Forked /nix/store/g0bxw4naz8gzx46p0gavh4p76r9dian5-http-getter/bin/http-getter as pid 17301
2018-06-07 09:10:48,860 [flent.runners] DEBUG: HTTP latency: Starting watchdog with timeout 90
2018-06-07 09:10:48,862 [flent.runners] DEBUG: Started TimerRunner idx 0 ('Watchdog [HTTP latency]')
2018-06-07 09:10:48,863 [flent.runners] DEBUG: Started HttpGetterRunner idx 0 ('HTTP latency')
2018-06-07 09:10:50,065 [flent.runners] WARNING: Program exited non-zero.
Runner class: HttpGetterRunner
Command: /nix/store/g0bxw4naz8gzx46p0gavh4p76r9dian5-http-getter/bin/http-getter -i 200 -l 60 -t 60000  -n 4 -6 http://%s/filelist.txt
Return code: 6
Stdout: -- OUTPUT START -->
Total 0 successful of 1 cycles. 0 total requests. min/avg/max = -1.000/-nan/-1.000 seconds.
<-- OUTPUT END --
Stderr: -- OUTPUT START -->cURL error: 'Couldn't resolve host name' while getting URL list at http://%s/filelist.txt.
<-- OUTPUT END --
2018-06-07 09:10:50,065 [flent.runners] WARNING: Command produced no valid data.
```

**Comment by tohojo** [comment]
Matthieu Coudron <notifications@github.com> writes:

> I wonder if there isn't an error at 
> https://github.com/tohojo/flent/blob/710f9f253944668b3d4200e1e3aa90cecba954db/flent/runners.py#L1251
> like it should be 
> ```
>                     or "http://{}/filelist.txt".format(self.settings.HOST))
> ```

Yup, you are quite right...

**Comment by teto** [comment]
if I may push my luck, I am discovering flent and wanna use it to plot cdf of completion transfer time. I couldn't find any test doing it and am trying to write one. I would rather have it out of tree. 
Is this the correct option https://flent.org/options.html#cmdoption-b ?

**Comment by tohojo** [comment]
Matthieu Coudron <notifications@github.com> writes:

> if I may push my luck, I am discovering flent and wanna use it to plot
> cdf of completion transfer time. I couldn't find any test doing it and
> am trying to write one. I would rather have it out of tree.
> Is this the correct option https://flent.org/options.html#cmdoption-b
> ?

Erm, probably not. Could you explain in a bit more detail what it is
you're trying to do? The HTTP tests already included already have a CDF
plot (it's just called delay instead of completion time; so the plot is
http_delay_cdf).

**Comment by teto** [comment]
I would like to send a fixed amount of data (I am more used to iperf) so for instance run 10 times ` iperf -c HOST -n 6MB` and show a cdf of the completion times.

I kinda understand the .conf format and came up with my own script:
```
DESCRIPTION="iperf completion delay 6MB"
DEFAULTS={'PLOT': "iperf_delay",
          'HOSTS': []}

IPERF_V6=""
if IP_VERSION == 6:
    IPERF_V6="-V"


DATA_SETS = o([
    ('TCP iperf',
        # -n => fixed number of byte
         {'command': "iperf -c %s -i %.2f -y C -n 6M %s" % (HOST, max(0.5,STEP_SIZE), IPERF_V6),
          'delay': DELAY,               # do I need this anymore ?
          'units': 'second',
          'runner': 'iperf_csv',})
    ])


PLOTS['iperf_delay']       = {'description': 'Iperf completion time',
                             'type': 'timeseries',
                             'series': [
                                 {'data': 'TCP iperf',
                                      'label': 'completion delay (ms)'}]}
    ],

```
My problem is on how to retrieve the actual data, i.e. the delay taken by the iperf connection. I see that the runners have a parse function and a self._raw_values 

Just for info here is the output.
```
iperf -n 6M -c localhost --enhancedreports
------------------------------------------------------------
Client connecting to localhost, TCP port 5001 with pid 20613
Write buffer size:  128 KByte
TCP window size: 2.50 MByte (default)
------------------------------------------------------------
[  3] local 127.0.0.1 port 46618 connected with 127.0.0.1 port 5001
[ ID] Interval        Transfer    Bandwidth       Write/Err  Rtry    Cwnd/RTT
[  3] 0.00-0.23 sec  6.00 MBytes   221 Mbits/sec  1/0      65483        0K/56811 us
```
