### ISSUE TITLE
[informational] FreeBSD port/package created

### ISSUE THREAD

**Issue by zi0r** [tohojo/flent#152]
I've created a FreeBSD port/package that will enable FreeBSD users to more quickly/easily get Flent installed/running:

[https://www.freshports.org/net/flent](https://www.freshports.org/net/flent)

**Comment by tohojo** [comment]
Ah, awesome, thanks!

Care to submit a patch to the documentation (doc/_templates/index.html
and doc/quickstart.rst) with a note for FreeBSD users? :)

**Comment by zi0r** [comment]
https://github.com/tohojo/flent/pull/153 created
