### ISSUE TITLE
Potential issues with matplotlib 3?

### ISSUE THREAD

**Issue by moeller0** [tohojo/flent#154]
I just updated my matplotlib from 2.X to 3 and it seems I have issues displaying results in the gui (from data files that do work with matplotlib 2.X):

Started Flent 1.2.2-git-27498cd using Python 3.6.7.
Initialised matplotlib v3.0.0 on numpy v1.15.2.
GUI loaded. Running on PyQt v5.11.2.
objc[20395]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff85eebc90) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11f185cd8). One of the two will be used. Which one is undefined.
ERROR: Aborting plotting due to error: 'NoneType' object has no attribute 'points_to_pixels'

**Comment by tohojo** [comment]
Things broke when matplotlib 2 was released, so wouldn't be surprised that the same thing happened for v3. I'll look into it :)
