### ISSUE TITLE
Flent GUI- problems plotting output

### ISSUE THREAD

**Issue by rayhammerco** [tohojo/flent#162]
Hello, Im trying to run Flent on MACos and am seeing the following errors. Im hoping someone can point me in the right direction on this. Thank you.

ERROR: Aborting plotting due to error: Error sending result: '<flent.plotters.BoxPlotter object at 0x118056898>'. Reason: 'AttributeError("'AxesSubplot' object has no attribute '_cachedRenderer'")'

pip3 list
Package         Version
--------------- -------
cycler          0.10.0 
flent           1.2.2  
kiwisolver      1.0.1  
matplotlib      3.1.0  
numpy           1.16.3 
pip             19.0.3 
pyparsing       2.4.0  
python-dateutil 2.8.0  
setuptools      40.8.0 
six             1.12.0 
wheel           0.33.1 
COSML-1547213:flent user49$ flent --version
Flent v1.2.2.
Running on Python 3.7.3 (default, Mar 27 2019, 09:23:15)  [Clang 10.0.1 (clang-1001.0.46.3)].
Using matplotlib version 3.1.0 on numpy 1.16.3.
Using PyQt5 version 5.10.1.

**Comment by tohojo** [comment]
rayhammerco <notifications@github.com> writes:

> Hello, Im trying to run Flent on MACos and am seeing the following
> errors. Im hoping someone can point me in the right direction on this.
> Thank you.

Hmm, I think this is fixed already; could you try the latest git version
and see if the problem persists, please?

**Comment by tohojo** [comment]
Ah, no it isn't! Seems there's a new bug with matplotlib 3.1... Will investigate!
