### ISSUE TITLE
tcp_rtt plots not working?

### ISSUE THREAD

**Issue by heistp** [tohojo/flent#163]
I have ss installed and am using --socket-stats, but for some reason tcp_rtt plots don't seem to be working (using rrul_be but I need it ultimately for tcp_1up_noping). I'm using flent from HEAD and python 3.7.3 on Ubuntu 19.04. Do the attached .flent.gz files and output from --verbose show what's going on?

[rrul_be-2019-06-06T154334.551187.flent.gz](https://github.com/tohojo/flent/files/3261829/rrul_be-2019-06-06T154334.551187.flent.gz)
[stderr.txt.gz](https://github.com/tohojo/flent/files/3261830/stderr.txt.gz)
[stdout.txt.gz](https://github.com/tohojo/flent/files/3261833/stdout.txt.gz)

**Comment by tohojo** [comment]
Pete Heist <notifications@github.com> writes:

> I have ss installed and am using --socket-stats, but for some reason
> tcp_rtt plots don't seem to be working (using rrul_be but I need it
> ultimately for tcp_1up_noping). I'm using flent from HEAD and python
> 3.7.3 on Ubuntu 19.04. Do the attached .flent.gz files and output from
> --verbose show what's going on?

Hmm, it looks like you 'ss' binary is not output'ing the PID associated
with the socket? Flent uses this to match the socket to the netperf
binary...

Maybe it's a permission thing? What's the output of `ss -tipn` as a
regular user and as root, respectively?

**Comment by heistp** [comment]
Ok, there is a difference there (below, sudo version contains pid at end of ESTAB line).

Running flent with sudo works even though I didn't used to need to do that on older Ubuntus. It's a fine workaround for now, only in addition, ss with my custom kernel doesn't show TCP RTT or a lot of other stats at all (third output below), so that could either be some needed kernel config or something else, so I'm off to figure out what that is. Thanks... :)

```
$ ss -tipn
State       Recv-Q         Send-Q                  Local Address:Port                 Peer Address:Port         
ESTAB       0              0                          10.72.0.37:22                     10.72.0.64:61418        
	 cubic wscale:5,7 rto:204 rtt:0.34/0.071 ato:80 mss:1448 pmtu:1500 rcvmss:1392 advmss:1448 cwnd:10 bytes_acked:13057 bytes_received:6621 segs_out:130 segs_in:230 data_segs_out:123 data_segs_in:105 send 340.7Mbps lastsnd:108364 lastrcv:108420 lastack:108364 pacing_rate 681.4Mbps delivery_rate 139.6Mbps app_limited busy:12ms rcv_space:14600 rcv_ssthresh:64076 minrtt:0.083
```

```
$ uname -a
Linux rey 5.0.0-16-generic #17-Ubuntu SMP Wed May 15 10:52:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ sudo ss -tipn
State       Recv-Q         Send-Q                  Local Address:Port                 Peer Address:Port         
ESTAB       0              0                          10.72.0.37:22                     10.72.0.64:61418         users:(("sshd",pid=9397,fd=3),("sshd",pid=9360,fd=3))
	 cubic wscale:5,7 rto:204 rtt:0.34/0.071 ato:80 mss:1448 pmtu:1500 rcvmss:1392 advmss:1448 cwnd:10 bytes_acked:13057 bytes_received:6621 segs_out:130 segs_in:230 data_segs_out:123 data_segs_in:105 send 340.7Mbps lastsnd:119880 lastrcv:119936 lastack:119880 pacing_rate 681.4Mbps delivery_rate 139.6Mbps app_limited busy:12ms rcv_space:14600 rcv_ssthresh:64076 minrtt:0.083
```

```
$ uname -a
Linux rey 5.1.0-rc2+ #63 SMP Mon Jun 3 17:45:55 CEST 2019 x86_64 x86_64 x86_64 GNU/Linux
$ sudo ss -tipn
State       Recv-Q        Send-Q                Local Address:Port                Peer Address:Port         
ESTAB       0             0                        10.72.0.36:22                    10.72.0.64:61660         users:(("sshd",pid=4006,fd=3),("sshd",pid=3937,fd=3)) rto:0.2 ato:0.11 qack:8 cwnd:10 reordering:0
```

**Comment by heistp** [comment]
Ah, that is very likely that CONFIG_INET_DIAG needs to be set, so I'll re-compile my kernel with that...

**Comment by heistp** [comment]
Yes, that's the case, so it's working now with the kernel compiled with CONFIG_INET_DIAG and as root. Closing this, unless you want me to test anything else...

**Comment by tohojo** [comment]
Pete Heist <notifications@github.com> writes:

> Ah, that is very likely that CONFIG_INET_DIAG needs to be set, so I'll
> re-compile my kernel with that...

Do let me know if that works; I don't get RTTs on my Arch kernel either,
it would seem (though I don't have the permission issue).

Will try to figure out if anything can be done about the permission thing...

**Comment by heistp** [comment]
More specifically, I set CONFIG_INET_DIAG, CONFIG_INET_UDP_DIAG and CONFIG_INET_RAW_DIAG, but it's probably only CONFIG_INET_DIAG that matters. Compiled as module also works.
