### ISSUE TITLE
Unable to use flent-gui from 83d14d68

### ISSUE THREAD

**Issue by heistp** [tohojo/flent#167]
I compiled on some new test boxes from head (83d14d68) and ran a test. flent -i for the text output worked but when I use flent -gui I see the following errors before it freezes:

```
ERROR: Error while loading data file: '<built-in function connectSlotsByName> returned a result with an error set'. Skipping.
ERROR: Error while loading data file: '<built-in function connectSlotsByName> returned a result with an error set'. Skipping.
```

**Comment by tohojo** [comment]
Pete Heist <notifications@github.com> writes:

> I compiled on some new test boxes from head (83d14d68) and ran a test. flent -i for the text output worked but when I use flent -gui I see the following errors before it freezes:
>
> ```
> ERROR: Error while loading data file: '<built-in function connectSlotsByName> returned a result with an error set'. Skipping.
> ERROR: Error while loading data file: '<built-in function connectSlotsByName> returned a result with an error set'. Skipping.
> ```

Uh, that's an interesting error!

What's the output of flent --version ?

**Comment by heistp** [comment]
Hmm, that made me realize it's working in Linux but not on my Mac, with slightly different versions of Python and PyQt5:

Not working (on MacOS 10.13.6):
```
% flent --version
Flent v1.9.9-git-83d14d6.
Running on Python 3.7.4 (default, Jul  9 2019, 18:15:00)  [Clang 10.0.0 (clang-1000.11.45.5)].
Using matplotlib version 3.1.1 on numpy 1.16.4.
Using PyQt5 version 5.12.3.
```

Working (on Ubuntu 19.04):
```
$ flent --version
Flent v1.9.9-git-83d14d6.
Running on Python 3.7.3 (default, Apr  3 2019, 05:39:12)  [GCC 8.3.0].
Using matplotlib version 3.1.1 on numpy 1.16.4.
Using PyQt5 version 5.12.1.
```

**Comment by tohojo** [comment]
Pete Heist <notifications@github.com> writes:

> Hmm, that made me realize it's working in Linux but not on my Mac, with slightly different versions of Python and PyQt5:
>
> Not working (on MacOS 10.13.6):
> ```
> % flent --version
> Flent v1.9.9-git-83d14d6.
> Running on Python 3.7.4 (default, Jul  9 2019, 18:15:00)  [Clang 10.0.0 (clang-1000.11.45.5)].
> Using matplotlib version 3.1.1 on numpy 1.16.4.
> Using PyQt5 version 5.12.3.
> ```

Ah, bugger, don't have a mac to test with. Guess you're in for an
interactive debugging session, then ;)

Do you get a backtrace if you're running with --verbose and
--debug-error ?

**Comment by heistp** [comment]
Sure, no problem :)...that does give some more info:

```
% flent-gui --verbose --debug-error *.flent.gz
Started Flent 1.9.9-git-83d14d6 using Python 3.7.4.
CACHEDIR=/Users/heistp/.matplotlib
Loaded backend agg version unknown.
Initialised matplotlib v3.1.1 on numpy v1.16.4.
GUI loaded. Running on PyQt v5.12.3.
Loading data file batch-two-flow-2019-07-15T130800-reno_reno-sce-sce-single-50Mbit-80ms.flent.gz
Loading data file batch-two-flow-2019-07-15T130800-reno-sce_reno-sce-sce-single-50Mbit-80ms.flent.gz
Executing test environment file /usr/local/lib/python3.7/site-packages/flent-1.9.9_git_83d14d6-py3.7.egg/flent/tests/tcp_2up.conf
Executing test environment file /usr/local/lib/python3.7/site-packages/flent-1.9.9_git_83d14d6-py3.7.egg/flent/tests/tcp_2up.conf
ERROR: Error while loading data file: '<built-in function connectSlotsByName> returned a result with an error set'. Skipping.
AttributeError: __getattribute__

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flent-1.9.9_git_83d14d6-py3.7.egg/flent/gui.py", line 837, in load_one
    widget = self.add_tab(r, t, current_plot, focus=False)
  File "/usr/local/lib/python3.7/site-packages/flent-1.9.9_git_83d14d6-py3.7.egg/flent/gui.py", line 777, in add_tab
    widget = ResultWidget(self.viewArea, self.settings, self.worker_pool)
  File "/usr/local/lib/python3.7/site-packages/flent-1.9.9_git_83d14d6-py3.7.egg/flent/gui.py", line 2072, in __init__
    super(ResultWidget, self).__init__(parent)
  File "/usr/local/lib/python3.7/site-packages/flent-1.9.9_git_83d14d6-py3.7.egg/flent/gui.py", line 224, in __init__
    self.setupUi(self)
  File "<string>", line 25, in setupUi
SystemError: <built-in function connectSlotsByName> returned a result with an error set
ERROR: Error while loading data file: '<built-in function connectSlotsByName> returned a result with an error set'. Skipping.
AttributeError: __getattribute__

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flent-1.9.9_git_83d14d6-py3.7.egg/flent/gui.py", line 837, in load_one
    widget = self.add_tab(r, t, current_plot, focus=False)
  File "/usr/local/lib/python3.7/site-packages/flent-1.9.9_git_83d14d6-py3.7.egg/flent/gui.py", line 777, in add_tab
    widget = ResultWidget(self.viewArea, self.settings, self.worker_pool)
  File "/usr/local/lib/python3.7/site-packages/flent-1.9.9_git_83d14d6-py3.7.egg/flent/gui.py", line 2072, in __init__
    super(ResultWidget, self).__init__(parent)
  File "/usr/local/lib/python3.7/site-packages/flent-1.9.9_git_83d14d6-py3.7.egg/flent/gui.py", line 224, in __init__
    self.setupUi(self)
  File "<string>", line 25, in setupUi
SystemError: <built-in function connectSlotsByName> returned a result with an error set
```

**Comment by heistp** [comment]
Against better judgment I upgraded PyQt5 to 5.13.0 on both the Mac and Linux and still see the problem on Mac but not on Linux, so that suggests it's not directly related to the PyQt 5 version.

**Comment by tohojo** [comment]
Pete Heist <notifications@github.com> writes:

> Against better judgment I upgraded PyQt5 to 5.13.0 on both the Mac and
> Linux and still see the problem on Mac but not on Linux, so that
> suggests it's not directly related to the PyQt 5 version.

Does it happen if you only load a single data file?

**Comment by heistp** [comment]
Yes, it does, then the symptom after the error (same with one or more files) is that Python is unresponsive and there's 100% CPU usage.

**Comment by flent-users** [comment]
Toke Høiland-Jørgensen <notifications@github.com> writes:

> Pete Heist <notifications@github.com> writes:
>
>> Against better judgment I upgraded PyQt5 to 5.13.0 on both the Mac and
>> Linux and still see the problem on Mac but not on Linux, so that
>> suggests it's not directly related to the PyQt 5 version.
>
> Does it happen if you only load a single data file?

I suspect this is a bug in PyQt... Could you try the qtpy branch,
please? That uses an abstraction library to make it possible to run on
different versions of python. You can set the QT_API environment
variable to different values to control which one is loaded; take a look
at https://github.com/spyder-ide/qtpy for the values.

It would be useful if you could try out the different ones and see in
which combination(s) the bug appears...

**Comment by heistp** [comment]
Ok, the problem doesn't happen with PySide2. It's likely with recent versions of PyQt5, although I'm not exactly sure of the first version where it started. It's also possible the bug doesn't happen on MacOS 10.14 (Mojave), but my 2011 hardware is pinned to 10.13 so I can't test that. So far I'm glad it's working now, but I can try another test if you want. BTW I think the qtpy commit is on the main branch...

**Comment by tohojo** [comment]
Pete Heist <notifications@github.com> writes:

> Ok, the problem doesn't happen with PySide2. It's likely with recent
> versions of PyQt5, although I'm not exactly sure of the first version
> where it started. It's also possible the bug doesn't happen on MacOS
> 10.14 (Mojave), but my 2011 hardware is pinned to 10.13 so I can't
> test that. So far I'm glad it's working now, but I can try another
> test if you want. BTW I think the qtpy commit is on the main branch...

Oh, right, pushed to the wrong branch... oops... well, guess I better go
fix the tests, then :)

Found another instance of what appears to be the same PyQt bug:
https://github.com/GNS3/gns3-gui/issues/2819

**Comment by heistp** [comment]
Ah, ok, well it looks like PySide2 has a more permissive license anyway, although I guess that shouldn't affect flent. I haven't noticed any other problems using it, although my testing has hardly been extensive.

**Comment by tohojo** [comment]
Pete Heist <notifications@github.com> writes:

> Ah, ok, well it looks like PySide2 has a more permissive license
> anyway, although I guess that shouldn't affect flent. I haven't
> noticed any other problems using it, although my testing has hardly
> been extensive.

Yeah, PySide2 are the officially supported Python bindings from upstream
Qt, so guess it's good to support that anyway (PyQt5 predates it
somewhat). And it's not a huge cost to carry the compatibility layer, so
I guess I can keep it like this...

**Comment by flent-users** [comment]
Okay, same issue on macosx 10.14.5. Now with the latest changes and PySide2 installed I get:


./run-flent --version
Flent v1.9.9-git-43e16d5.
Running on Python 3.7.4 (default, Jul 11 2019, 01:08:00)  [Clang 10.0.1 (clang-1001.0.46.4)].
Using matplotlib version 3.1.1 on numpy 1.16.4.
Using PyQt5 version 5.12.2.



./run-flent --gui
Started Flent 1.9.9-git-43e16d5 using Python 3.7.4.
ERROR: Unable to find a usable Qt version.

Same Qt version "worked" before the latest changes; the quotes as I saw the same error as Pete.

If I can do anything on my side to fix/debug this, please let me know. Also let me know if I am just stupid and dod something wrong...


Best Regards
	Sebastian

**Comment by flent-users** [comment]
Sebastian Moeller <moeller0@gmx.de> writes:

> Okay, same issue on macosx 10.14.5. Now with the latest changes and PySide2 installed I get:
>
>
> ./run-flent --version
> Flent v1.9.9-git-43e16d5.
> Running on Python 3.7.4 (default, Jul 11 2019, 01:08:00)  [Clang 10.0.1 (clang-1001.0.46.4)].
> Using matplotlib version 3.1.1 on numpy 1.16.4.
> Using PyQt5 version 5.12.2.
>
>
>
> ./run-flent --gui
> Started Flent 1.9.9-git-43e16d5 using Python 3.7.4.
> ERROR: Unable to find a usable Qt version.
>
> Same Qt version "worked" before the latest changes; the quotes as I
> saw the same error as Pete.

You probably need to 'pip install QtPy' first... Will try to document
that somewhere :)

**Comment by flent-users** [comment]
Mmmh, so I installed qtpy (and dependencies) I now get:

./run-flent --gui
Started Flent 1.9.9-git-43e16d5 using Python 3.7.4.
Initialised matplotlib v3.1.1 on numpy v1.16.4.
GUI loaded. Using Qt through pyqt5 v5.12.3.
objc[13628]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9b6ec3d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x12662cf50). One of the two will be used. Which one is undefined.
ERROR: Error while loading data file: '<built-in function connectSlotsByName> returned a result with an error set'. Skipping.

The GUI opens again, but I still see the same lock-up that Pete initially saw. Going to bed for now, maybe I find time to poke this tomorrow...

Thanks!

**Comment by heistp** [comment]
It looks like it was still using PyQt5 in your case, so make sure to first do:

```
export QT_API= pyside2
```

If this is a long-term fix for Mac, maybe that var could be set on MacOS when sys.platform is darwin, assuming we have a chance to do so before those libs are initialized. Probably best would be if they fixed PyQt5. :)

**Comment by flent-users** [comment]
Sebastian Moeller <moeller0@gmx.de> writes:

> Mmmh, so I installed qtpy (and dependencies) I now get:
>
> ./run-flent --gui
> Started Flent 1.9.9-git-43e16d5 using Python 3.7.4.
> Initialised matplotlib v3.1.1 on numpy v1.16.4.
> GUI loaded. Using Qt through pyqt5 v5.12.3.
> objc[13628]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9b6ec3d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x12662cf50). One of the two will be used. Which one is undefined.
> ERROR: Error while loading data file: '<built-in function connectSlotsByName> returned a result with an error set'. Skipping.
>
> The GUI opens again, but I still see the same lock-up that Pete
> initially saw. Going to bed for now, maybe I find time to poke this
> tomorrow...

Well, you'll still need to switch from PyQt5 to PySide2 - installing the
latter is not enough, sadly, you'll also need to either set the QT_API
environment variable, or uninstall PyQt5...

-Toke

**Comment by heistp** [comment]
```
export QT_API=pyside2
```

A space had crept in my previous post after the equals. :)

**Comment by tohojo** [comment]
Pete Heist <notifications@github.com> writes:

> It looks like it was still using PyQt5 in your case, so make sure to first do:
>
> ```
> export QT_API= pyside2
> ```
>
> If this is a long-term fix for Mac, maybe that var could be set on
> MacOS when sys.platform is darwin, assuming we have a chance to do so
> before those libs are initialized. Probably best would be if they
> fixed PyQt5. :)

Yeah, I'm not really sure what the long-term solution should be. I guess
I can try sending an email to the PyQt5 mailing list and see if anyone
responds...

**Comment by flent-users** [comment]
Thank you very much, both Toke ans Pete:

QT_API=pyside2 ./run-flent --gui
did the trick, now I guess I either write a small wrapper around run-flent or simply put the export in my .bashrc.

Anyway with this the GUI runs and loads data files again.

Again Best Regards & Thanks

**Comment by bicobus** [comment]
Isn't there a bugtracker for PyQt5 somewhere or is the only way to reach riverbankcomputing to post on their mailing list?

**Comment by tohojo** [comment]
Bicobus <notifications@github.com> writes:

> Isn't there a bugtracker for PyQt5 somewhere or is the only way to
> reach riverbankcomputing to post on their mailing list?

Couldn't find one. Which is one of the reasons why I figure it's a good
idea to focus on pyside2 instead :)

**Comment by bicobus** [comment]
A working example of a workaround the issue by compiling the ui files with pyuic5, here in a ui_testui.py file.

```python
from PyQt5 import QtWidgets
from .ui_testui import Ui_TestUi

class TestUi(QtWidgets.Qwidget):
    def __init__(self, parent=None):
        super(TestUi, self).__init__(parent)
        self.ui = Ui_TestUi()
        self.ui.setupUi(self)
```

It would be best to contact riverbankcomputing, I believe.

**Comment by jstnlef** [comment]
I'm seeing the same there here. An interesting thing to note is that this seems to be an issue with PyQt5 and python 3.7.4. When running with python 3.7.3, I'm not seeing the issue.

**Comment by tohojo** [comment]
Justin LeFebvre <notifications@github.com> writes:

> I'm seeing the same there here. An interesting thing to note is that
> this seems to be an issue with PyQt5 and python 3.7.4. When running
> with python 3.7.3, I'm not seeing the issue.

Ah, that's interesting! Still not something that's likely we can work
around from Flent, though :(

**Comment by bicobus** [comment]
Has been reported and should be fixed in the current snapshot (and thus for the following release)

Thread: https://www.riverbankcomputing.com/pipermail/pyqt/2019-August/042003.html

Quoting Phil Thompson:
> It could also be that an exception is being correctly ignored, but not cleared with PyErr_Clear().
>
> However I can't reproduce the problem - I don't get a traceback, although I'm not using exactly the same versions of Python.

Phil probably tested with the previous iteration of python and didn't get the issue.

**Comment by hnyman** [comment]
Was this ever solved?

I have not been able to use flent-gui in my Ubuntu 19.10 that is used for Openwrt buildhost.
Flent 1.3.2 using Python 3.7.5 and PyQt v5.12.3.

flent-gui gets stuck and needs to get killed:
`ERROR: Error while loading data file: '<built-in function connectSlotsByName> returned a result with an error set'. Skipping.`


Full context on console:
```
flent ipv4 150s netperf-eu.bufferbloat.net R7800_koe_koe_koe_koe
Started Flent 1.3.2 using Python 3.7.5.
Starting rrul test. Expected run time: 160 seconds.
Data file written to ./rrul-2020-01-04T124404.775287.R7800_koe_koe_koe_koe.flent.gz.
Initialised matplotlib v3.0.2 on numpy v1.16.2.
la 4.1.2020 12.46.50 +0200

perus@ub1910:/Openwrt/flent$ flent-gui 
Started Flent 1.3.2 using Python 3.7.5.
Initialised matplotlib v3.0.2 on numpy v1.16.2.
GUI loaded. Running on PyQt v5.12.3.
ERROR: Error while loading data file: '<built-in function connectSlotsByName> returned a result with an error set'. Skipping.
Killed
```

I did not figure out the correct way to get flent results displayed :-( 
Any pointers?

**Comment by tohojo** [comment]
Try upgrading your PyQt version, or switching to PySide2. Didn't find a way to work around this bug in Flent, unfortunately...
