### ISSUE TITLE
Two latency measurement flows with different tos byte for each?

### ISSUE THREAD

**Issue by heistp** [tohojo/flent#169]
Is there a way I could start two latency measurement flows, either both ICMP or both UDP (ideally it should be the same), each of which has a different value for the tos field, alongside the tcp_nup test?

**Comment by tohojo** [comment]
Pete Heist <notifications@github.com> writes:

> Is there a way I could start two latency measurement flows, either
> both ICMP or both UDP (ideally it should be the same), each of which
> has a different value for the tos field, alongside the tcp_nup test?

See 878f297cd336539189fe577ea82c1037ed136b20 which adds the
ping_markings test parameter; you can add extra ping flows and set their
markings...

**Comment by heistp** [comment]
Thanks! That's working over the wire, and I've managed to add plots for throughput+pings and delivery+pings, so this is working.

In general, is it worth upstreaming such custom plots? If I don't, I sometimes forget and blow them away when cloning a fresh tree, moving to a new box, etc. :)

**Comment by tohojo** [comment]
Pete Heist <notifications@github.com> writes:

> Thanks! That's working over the wire, and I've managed to add plots
> for throughput+pings and delivery+pings, so this is working.

Awesome!

> In general, is it worth upstreaming such custom plots? If I don't, I
> sometimes forget and blow them away when cloning a fresh tree, moving
> to a new box, etc. :)

Yes, feel free to submit pull requests for these things!
