### ISSUE TITLE
I think it should be [enable] log scale

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#17]
I generally never use the log scales except on pfifo_fast.

If you inverted the sense of the test you could use "log scale" for the check box.

**Comment by tohojo** [comment]
Well the idea is that there's a heuristic to only add the log scale if the data warrants it. Currently, the heuristic is a span of more than a factor of 20...

But in general, I'd like all options to have both on- and off variants. Might be worth looking at the defaults while implementing that...

**Comment by tohojo** [comment]
Related to #23.
