### ISSUE TITLE
Stable output filenames for batch runs

### ISSUE THREAD

**Issue by heistp** [tohojo/flent#179]
Currently, the output filenames for batches always include `batch_time`:

```
    def gen_filename(self, settings, batch, argset, rep):
        filename = "batch-%s-%s-%s" % (
            settings.BATCH_NAME,
            batch['batch_time'],
            batch.get('filename_extra', "%s-%s" % (argset, rep))
        )
        return clean_path(filename)
```

On one hand, this ensures that output filenames are unique, but on the other hand, one can't create stable links to the output filenames that don't change between runs, for example in a static HTML or markdown file.

What I could do is add a `filename_no_time` or similar parameter that if set to anything "truthy" (maybe if s in [ '1', 'true', 'yes' ]), excludes the time from the filename, then it's up to people to properly set `filename_extra`.

Would you be ok if I do that, or do you have any other suggestions for this?

**Comment by flent-users** [comment]
> On Sep 6, 2019, at 15:23, Pete Heist <notifications@github.com> wrote:
> 
> Currently, the output filenames for batches always include batch_time:
> 
>     def gen_filename(self, settings, batch, argset, rep):
>         filename = "batch-%s-%s-%s" % (
>             settings.BATCH_NAME,
>             batch['batch_time'],
>             batch.get('filename_extra', "%s-%s" % (argset, rep))
>         )
>         return clean_path(filename)
> 
> On one hand, this ensures that output filenames are unique, but on the other hand, one can't create stable links to the output filenames that don't change between runs, for example in a static HTML or markdown file.
> 
> What I could do is add a filename_no_time or similar parameter that if set to anything "truthy" (maybe if s in [ '1', 'true', 'yes' ]), excludes the time from the filename, then it's up to people to properly set filename_extra.

	You could just create a symbolic link most_recent_batch_result put a link to this into the html/md and just update the symbolic link once a batch has run, no?

Best Regards
	Sebastian

**Comment by dtaht** [comment]
Pete Heist <notifications@github.com> writes:

> Currently, the output filenames for batches always include batch_time:
>
>     def gen_filename(self, settings, batch, argset, rep):
>         filename = "batch-%s-%s-%s" % (
>             settings.BATCH_NAME,
>             batch['batch_time'],
>             batch.get('filename_extra', "%s-%s" % (argset, rep))
>         )
>         return clean_path(filename)
>
> On one hand, this ensures that output filenames are unique, but on the
> other hand, one can't create stable links to the output filenames that
> don't change between runs, for example in a static HTML or markdown
> file.
>
> What I could do is add a filename_no_time or similar parameter that if
> set to anything "truthy" (maybe if s in [ '1', 'true', 'yes' ]),
> excludes the time from the filename, then it's up to people to
> properly set filename_extra.
>
> Would you be ok if I do that, or do you have any other suggestions for
> this?

--no-time

**Comment by heistp** [comment]
I'd prefer the `--no-time` flag fwiw, simpler and more visible.

Symlinks could help in some cases, but the challenges for me are:
- there'd need to be one per individual test run (i.e. many per batch)
- one needs to take care to maintain symlinks when doing scp, rsync, etc
- I have supporting files that share the same base name as the .flent.gz file which would also need to be symlinked, so it could get to be many symlinks :)

**Comment by tohojo** [comment]
> Would you be ok if I do that, or do you have any other suggestions for
> this?

Not opposed to having an option; --batch-no-timestamp ?

**Comment by heistp** [comment]
Added in 2d0d8fbd844b2f2153f098e157294983e3432dc7, thanks for accepting.
