### ISSUE TITLE
csv stats output with wildcards

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#18]
I was delighted to see I could output all the statistics in a given batch with:

 netperf-wrapper -f csv tcp_upload*.json.gz

However having the first bit of output have column names, and the left side the filename, would be useful when importing into a spreadsheet.

**Comment by tohojo** [comment]
On 8 April 2015 09:04:25 CEST, "Dave Täht" <notifications@github.com> wrote:
> I was delighted to see I could output all the statistics in a given
> batch with:
> 
>  netperf-wrapper -f csv tcp_upload*.json.gz
> 
> However having the first bit of output have column names, and the left
> side the filename, would be useful when importing into a spreadsheet.

As in repeat the headers for each file and stick the filename in there?

**Comment by dtaht** [comment]
filename in the first column, headers in the first row.

**Comment by tohojo** [comment]
Dave Täht <notifications@github.com> writes:

> filename in the first column, headers in the first row.

There's already headers output in the first row? How would you want them
to be different?
