### ISSUE TITLE
Aborting plotting due to error

### ISSUE THREAD

**Issue by acdcjavier** [tohojo/flent#187]
Hello
I've installed flent into a fresh Ubuntu 19 but when I make a test, got this error

Aborting plotting due to error: 'NoneType' object has no attribute 'points_to_pixels'

I need to install someting extra??

**Comment by tohojo** [comment]
acdcjavier <notifications@github.com> writes:

> Hello
> I've installed flent into a fresh Ubuntu 19 but when I make a test, got this error
>
> Aborting plotting due to error: 'NoneType' object has no attribute 'points_to_pixels'
>
> I need to install someting extra??

This sounds like a bug. What's the output of flent --version ?

-Toke

**Comment by acdcjavier** [comment]
> acdcjavier <notifications@github.com> writes:
> Hello I've installed flent into a fresh Ubuntu 19 but when I make a test, got this error Aborting plotting due to error: 'NoneType' object has no attribute 'points_to_pixels' I need to install someting extra??
> This sounds like a bug. What's the output of flent --version ?
> […](#)
> -Toke

Flent v1.3.0.
Running on Python 3.7.5rc1 (default, Oct  8 2019, 16:47:45)  [GCC 9.2.1 20191008].
Using matplotlib version 3.0.2 on numpy 1.16.2.
Using PyQt5 version 5.12.3.


Also, when I make a test using commands, and I open the graph throught the application, it freezes and I can't close, must force reboot.

**Comment by tohojo** [comment]
acdcjavier <notifications@github.com> writes:

>> acdcjavier <notifications@github.com> writes:
>> Hello I've installed flent into a fresh Ubuntu 19 but when I make a test, got this error Aborting plotting due to error: 'NoneType' object has no attribute 'points_to_pixels' I need to install someting extra??
>> This sounds like a bug. What's the output of flent --version ?
>> […](#)
>> -Toke
>
> Flent v1.3.0.
> Running on Python 3.7.5rc1 (default, Oct  8 2019, 16:47:45)  [GCC 9.2.1 20191008].
> Using matplotlib version 3.0.2 on numpy 1.16.2.
> Using PyQt5 version 5.12.3.

Could you please try the git version of Flent and see if the same bug is
present there? You should be able to just clone the repository and use
the `run-flent` script in place of the system-installed version.

**Comment by acdcjavier** [comment]
> Could you please try the git version of Flent and see if the same bug is present there? You should be able to just clone the repository and use the `run-flent` script in place of the system-installed version.

Ok, but do I need to remove flent system-installed version?

**Comment by tohojo** [comment]
acdcjavier <notifications@github.com> writes:

>> Could you please try the git version of Flent and see if the same bug is present there? You should be able to just clone the repository and use the `run-flent` script in place of the system-installed version.
>
> Ok, but do I need to remove flent system-installed version?

Not for testing; you can just run the ./run-flent script and it'll
ignore the system-installed version...

**Comment by acdcjavier** [comment]
> acdcjavier <notifications@github.com> writes:
> > Could you please try the git version of Flent and see if the same bug is present there? You should be able to just clone the repository and use the `run-flent` script in place of the system-installed version. Ok, but do I need to remove flent system-installed version?
> Not for testing; you can just run the ./run-flent script and it'll ignore the system-installed version...

Thanks but got this error
Sorry, Flent requires v3.5 or later of Python.

But I have phyton 3.7...

**Comment by flent-users** [comment]
> On Oct 15, 2019, at 14:52, acdcjavier <notifications@github.com> wrote:
> 
> acdcjavier notifications@github.com writes:
> 
> Could you please try the git version of Flent and see if the same bug is present there? You should be able to just clone the repository and use the run-flent script in place of the system-installed version. Ok, but do I need to remove flent system-installed version?
> Not for testing; you can just run the ./run-flent script and it'll ignore the system-installed version...
> 
> Thanks but got this error
> Sorry, Flent requires v3.5 or later of Python.
> 
> But I have phyton 3.7...

What do you see when you type:
python --version
on the command line? My wild guess is that the system python still is python 2.7 or so, when I ran into the same problem I manually edited the run-flent script to start with:
#!/usr/bin/env python3.7

as on my mac python still defaults to 2.7.

Hope that helps.

	Sebastian

**Comment by tohojo** [comment]
acdcjavier <notifications@github.com> writes:

>> acdcjavier <notifications@github.com> writes:
>> > Could you please try the git version of Flent and see if the same bug is present there? You should be able to just clone the repository and use the `run-flent` script in place of the system-installed version. Ok, but do I need to remove flent system-installed version?
>> Not for testing; you can just run the ./run-flent script and it'll ignore the system-installed version...
>
> Thanks but got this error
> Sorry, Flent requires v3.5 or later of Python.
>
> But I have phyton 3.7...

Ah yes, that is a bug. I just pushed a fix for this, so please do a 'git
pull' and then try again :)

**Comment by acdcjavier** [comment]
> On Oct 15, 2019, at 14:52, acdcjavier ***@***.***> wrote: acdcjavier ***@***.*** writes: Could you please try the git version of Flent and see if the same bug is present there? You should be able to just clone the repository and use the run-flent script in place of the system-installed version. Ok, but do I need to remove flent system-installed version? Not for testing; you can just run the ./run-flent script and it'll ignore the system-installed version... Thanks but got this error Sorry, Flent requires v3.5 or later of Python. But I have phyton 3.7...
> What do you see when you type: python --version on the command line? My wild guess is that the system python still is python 2.7 or so, when I ran into the same problem I manually edited the run-flent script to start with: #!/usr/bin/env python3.7 as on my mac python still defaults to 2.7. Hope that helps. Sebastian
> […](#)
> — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. _______________________________________________ Flent-users mailing list ***@***.*** http://flent.org/mailman/listinfo/flent-users_flent.org

Hello
Yes, mine still shows 2.7

**Comment by acdcjavier** [comment]
> acdcjavier <notifications@github.com> writes:
> > acdcjavier ***@***.***> writes: > > Could you please try the git version of Flent and see if the same bug is present there? You should be able to just clone the repository and use the `run-flent` script in place of the system-installed version. Ok, but do I need to remove flent system-installed version? > Not for testing; you can just run the ./run-flent script and it'll ignore the system-installed version... Thanks but got this error Sorry, Flent requires v3.5 or later of Python. But I have phyton 3.7...
> Ah yes, that is a bug. I just pushed a fix for this, so please do a 'git pull' and then try again :)

Now got this error xD

./run-flent
Started Flent 1.9.9-git-edfc0e0 using Python 3.7.5rc1.
ERROR: Missing test name.

**Comment by acdcjavier** [comment]
> acdcjavier <notifications@github.com> writes:
> > acdcjavier ***@***.***> writes: > > Could you please try the git version of Flent and see if the same bug is present there? You should be able to just clone the repository and use the `run-flent` script in place of the system-installed version. Ok, but do I need to remove flent system-installed version? > Not for testing; you can just run the ./run-flent script and it'll ignore the system-installed version... Thanks but got this error Sorry, Flent requires v3.5 or later of Python. But I have phyton 3.7...
> Ah yes, that is a bug. I just pushed a fix for this, so please do a 'git pull' and then try again :)

Working now using RRUL testing, it creates the .png file 
But when I opened the flent.gz file using GUI interface, it freeze Ubuntu and must force reboot.

Also, when I perform a "Ping" test, got this error:

./run-flent ping -p all_scaled -l 10 -H netperf.bufferbloat.net -t text-to-be-included-in-plot -o prueba.png

Started Flent 1.9.9-git-edfc0e0 using Python 3.7.5rc1.
Starting ping test. Expected run time: 10 seconds.
Data file written to ./ping-2019-10-15T105435.560049.text-to-be-included-in-plot.flent.gz
Initialised matplotlib v3.0.2 on numpy v1.16.2.
ERROR: Error loading plotter: Unable to find plot configuration 'all_scaled'

**Comment by tohojo** [comment]
acdcjavier <notifications@github.com> writes:

>> acdcjavier <notifications@github.com> writes:
>> > acdcjavier ***@***.***> writes: > > Could you please try the git version of Flent and see if the same bug is present there? You should be able to just clone the repository and use the `run-flent` script in place of the system-installed version. Ok, but do I need to remove flent system-installed version? > Not for testing; you can just run the ./run-flent script and it'll ignore the system-installed version... Thanks but got this error Sorry, Flent requires v3.5 or later of Python. But I have phyton 3.7...
>> Ah yes, that is a bug. I just pushed a fix for this, so please do a 'git pull' and then try again :)
>
> Working now using RRUL testing, it creates the .png file 
> But when I opened the flent.gz file using GUI interface, it freeze Ubuntu and must force reboot.
>
> Also, when I perform a "Ping" test, got this error:
>
> ./run-flent ping -p all_scaled -l 10 -H netperf.bufferbloat.net -t text-to-be-included-in-plot -o prueba.png
>
> Started Flent 1.9.9-git-edfc0e0 using Python 3.7.5rc1.
> Starting ping test. Expected run time: 10 seconds.
> Data file written to ./ping-2019-10-15T105435.560049.text-to-be-included-in-plot.flent.gz
> Initialised matplotlib v3.0.2 on numpy v1.16.2.
> ERROR: Error loading plotter: Unable to find plot configuration
> 'all_scaled'

This means exactly what it says - there's not 'all_scaled' plot for the
'ping' test. So try with '-p ping' instead :)
