### ISSUE TITLE
SERIES_META doesn't container required fields

### ISSUE THREAD

**Issue by smalleni** [tohojo/flent#189]
Running flent as in
```
 flent -H 10.0.0.183 -l 60 -s 1 tcp_download
```

In the resulting output, 

SERIES_META doesn't have the required fields
    "SERIES_META": {
      "Ping (ms) ICMP": {}, 
      "TCP download": {}
    },

Earlier, SERIES_META used to have something like,
"SERIES_META": {\n      "Ping (ms) ICMP": {\n        "MAX_VALUE": 4.043, \n        "MEAN_VALUE": 1.935, \n        "MIN_VALUE": 0.115, \n        "UNITS": "ms"\n      }, \n      "TCP download": {\n        "MEAN_VALUE": 9931.61, \n        "UNITS": "Mbits/s"\n      }\n    }

flent version being used is 1.3.0

**Comment by smalleni** [comment]
Looks like https://github.com/tohojo/flent/commit/ff465203dd7de78d87e0d88717068621b8159c28 has the fix. Since we consume flent from pip in https://opendev.org/performa/shaker we don't have this change. @tohojo any estimate on when there will be a new pip package?

**Comment by tohojo** [comment]
Sai Sindhur Malleni <notifications@github.com> writes:

> Looks like
> https://github.com/tohojo/flent/commit/ff465203dd7de78d87e0d88717068621b8159c28
> has the fix. Since we consume flent from pip in
> https://opendev.org/performa/shaker we don't have this change. @tohojo
> any estimate on when there will be a new pip package?

Hmm, yeah, guess I should make another release with that; will try to
get around to it soonish...

**Comment by smalleni** [comment]
@tohojo Thanks!

**Comment by tohojo** [comment]
Sorry for taking so long; release 1.3.1 should be making its way to PyPi now :)
