### ISSUE TITLE
CS5 does not appear to be emitted by the rrul test with irtt

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#190]
Attached is a packet capture showing that cs1, cs0, and ef are being successfully set on the rrul test for irtt. cs5 (the vi queue in wifi), isn't.

(it also shows that comcast remarks ef to cs0)
[rrul-2019-11-16T101614.379448.flent.gz](https://github.com/tohojo/flent/files/3854545/rrul-2019-11-16T101614.379448.flent.gz)

[no-cs5.pcap.gz](https://github.com/tohojo/flent/files/3854548/no-cs5.pcap.gz)

@heistp @tohojo 

for the record this is a server (flent-singapore.taht.net) running a stock nanode instance with ubuntu 19.10 and kernel 5.3.x, no other mods.

irtt alone does appear to be able to successfully set cs5 --dscp=a0

**Comment by tohojo** [comment]
According to the metadata, Netperf thinks it is setting the TOS to 0xA0
as it's supposed to...

**Comment by dtaht** [comment]
Duh. The flent rrul test isn't defined to test CS5 over udp. Sigh.

**Comment by flent-users** [comment]
Try rrul_cs8?

On November 16, 2019 11:18:38 PM GMT+01:00, "Dave Täht" <notifications@github.com> wrote:
>Duh. The flent rrul test isn't defined to test CS5 over udp. Sigh.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tohojo/flent/issues/190#issuecomment-554679575

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
