### ISSUE TITLE
Plot 'ping' failed: Error loading plotter

### ISSUE THREAD

**Issue by loko-it** [tohojo/flent#193]
I'am using flent 1.3.2 on Ubuntu 18 and it works perfect except for the voip test. It will give this error:

ERROR: Plot 'ping' failed: Error loading plotter: Unable to find plot configuration 'ping'. Falling back to default plot 'voip_delay'.

Anybody knows how to fix this?

**Comment by tohojo** [comment]
What were you trying to do when you got this error?

**Comment by loko-it** [comment]
First of all thank you for responding.

I use the GUI and select the VOIP, one way stream test to this server flent-london.bufferbloat.net
It will give the error but still show a graph only it seems the off.
The voip delay is giving over 200ms but normal ping is 15ms. But it could also be the server i am using for this test.

In the end i like to test voip and then voip with rrul to see the difference under load and the fact there is a MOS score is also interesting.

**Comment by tohojo** [comment]
loko-it <notifications@github.com> writes:

> First of all thank you for responding.
>
> I use the GUI and select the VOIP, one way stream test to this server flent-london.bufferbloat.net
> It will give the error but still show a graph only it seems the off.
> The voip delay is giving over 200ms but normal ping is 15ms. But it could also be the server i am using for this test.
>
> In the end i like to test voip and then voip with rrul to see the
> difference under load and the fact there is a MOS score is also
> interesting.

Hmm, could you please share the data file produced by your test run?
Can't immediately reproduce this when I'm running a test myself...
