### ISSUE TITLE
flent tries to use fping -6 on 1.1.1.1

### ISSUE THREAD

**Issue by richb-hanover** [tohojo/flent#194]
My coffee-shop-speed-test.sh started to give an error message: `1.1.1.1: nodename nor servname provided, or not known` This appears to occur because `fping -6` attempts to ping an IPv4 address, 1.1.1.1. (see full output below).

This doesn't happen when I set `--te_ping_hosts=2606:4700:4700::1111` in the flent command - it runs without errors. 

I haven't changed the script (that calls flent) for a while. Why might this error have cropped up recently? (I had been using `Flent 1.9.9-git-fa47b0f using Python 3.7.3.` I upgraded today to `Flent 1.9.9-git-25af65f ` to see if that made a difference. Both produce the error. Thanks.

```
bash-3.2$ flent -x -H flent-fremont.bufferbloat.net -t "Home" --te=ping_hosts=1.1.1.1 --te=download_streams=4 tcp_ndown
Started Flent 1.9.9-git-25af65f using Python 3.7.4.
Starting tcp_ndown test. Expected run time: 70 seconds.
WARNING: Program exited non-zero.
Runner class: PingRunner
Command: /usr/local/sbin/fping -6 -D -p 200 -c 350 -t 140000   1.1.1.1
Return code: 2
Stdout:
Stderr: 1.1.1.1: nodename nor servname provided, or not known

WARNING: Command produced no valid data.
Runner class: PingRunner
Command: /usr/local/sbin/fping -6 -D -p 200 -c 350 -t 140000   1.1.1.1
Return code: 2
Stdout:
Stderr: 1.1.1.1: nodename nor servname provided, or not known

Data file written to ./tcp_ndown-2020-01-31T011030.307579.Home.flent.gz

Summary of tcp_ndown test run from 2020-01-31 06:10:30.307579
  Title: 'Home'

                                           avg       median          # data pts
 Ping (ms) ICMP                 :       102.00       103.00 ms              353
 Ping (ms) ICMP 1.1.1.1 (extra) : No data.
 TCP download avg               :         1.55          N/A Mbits/s         353
 TCP download sum               :         6.22          N/A Mbits/s         353
 TCP download::1                :         1.63         1.68 Mbits/s         353
 TCP download::2                :         1.31         1.30 Mbits/s         353
 TCP download::3                :         1.86         1.93 Mbits/s         353
 TCP download::4                :         1.42         1.45 Mbits/s         353
bash-3.2$
```

**Comment by tohojo** [comment]
Hmm, I think this is because Flent will do hostname resolution of the
main test host and use the same v4/v6 decision for the ping_hosts. I
guess that needs to be relaxed so IP versions can be mixed (in the
absence of explicit v4/v6 command-line switches)

**Comment by richb-hanover** [comment]
OK. There's a nice workaround (or hack, I'm not sure which). Cloudflare's DNS resolver lives at the name "one.one.one.one" (really!) dig returns either of these, depending on whether you ask for "a" or "aaaa":

# IPv4: 1.1.1.1 or 1.0.0.1 
# IPv6: 2606:4700:4700::1111 or 2606:4700:4700::1001

I tweaked the script to pass in "one.one.one.one" and no more errors. (https://github.com/richb-hanover/coffee-shop-bloat-test)

Thanks.
