### ISSUE TITLE
Problems with the size code?

### ISSUE THREAD

**Issue by moeller0** [tohojo/flent#197]
Probably a pilot's error, but with current master i get:
```
mac:flent user$ ./run-flent-gui.sh 
Traceback (most recent call last):
  File "./run-flent", line 33, in <module>
    sys.exit(run_flent())
  File "/space/data_local/moeller/PRIVATE/samba/privat/MOEWE/techno_kram/CODE/flent/flent/__init__.py", line 53, in run_flent
    settings = load(sys.argv[1:])
  File "/space/data_local/moeller/PRIVATE/samba/privat/MOEWE/techno_kram/CODE/flent/flent/settings.py", line 773, in load
    settings.update_implications()
  File "/space/data_local/moeller/PRIVATE/samba/privat/MOEWE/techno_kram/CODE/flent/flent/settings.py", line 747, in update_implications
    if len(self.SEND_SIZE) == 1 and len(self.HOSTS) > 1:
TypeError: object of type 'NoneType' has no len()
```

**Comment by tohojo** [comment]
moeller0 <notifications@github.com> writes:

> Probably a pilot's error, but with current master i get:
> ```
> mac:flent user$ ./run-flent-gui.sh 
> Traceback (most recent call last):
>   File "./run-flent", line 33, in <module>
>     sys.exit(run_flent())
>   File "/space/data_local/moeller/PRIVATE/samba/privat/MOEWE/techno_kram/CODE/flent/flent/__init__.py", line 53, in run_flent
>     settings = load(sys.argv[1:])
>   File "/space/data_local/moeller/PRIVATE/samba/privat/MOEWE/techno_kram/CODE/flent/flent/settings.py", line 773, in load
>     settings.update_implications()
>   File "/space/data_local/moeller/PRIVATE/samba/privat/MOEWE/techno_kram/CODE/flent/flent/settings.py", line 747, in update_implications
>     if len(self.SEND_SIZE) == 1 and len(self.HOSTS) > 1:
> TypeError: object of type 'NoneType' has no len()
> ```

No, you're right, that's a bug. Should be fixed now - thanks for reporting! :)

**Comment by moeller0** [comment]
Excellent, thanks it works now.
