### ISSUE TITLE
box plots missing boxes

### ISSUE THREAD

**Issue by heistp** [tohojo/flent#198]
In flent from head (1.9.9-git-3d663cf) I seem to be missing the boxes on box plots, like the attached image. I'm mostly doing tcp_nup and tcp_1up. It's the same on Linux and MacOS. I'll send a .flent.gz in case that helps.

![Screen Shot 2020-02-16 at 11 27 22 PM](https://user-images.githubusercontent.com/4397233/74613974-ef586e80-5113-11ea-98ec-25407b2e75a0.png)

**Comment by tohojo** [comment]
Pete Heist <notifications@github.com> writes:

> In flent from head (1.9.9-git-3d663cf) I seem to be missing the boxes
> on box plots, like the attached image. I'm mostly doing tcp_nup and
> tcp_1up. It's the same on Linux and MacOS. I'll send a .flent.gz in
> case that helps.

That image just looks like what happens when the boxes get squeezed
together because there's only a single data point?

**Comment by heistp** [comment]
Ah, I understand now that that the boxes would appear when there are multiple repetitions in the batch run. I thought they might show the variances in data for each flow. While that could be useful, it looks like I can get what I actually need at the moment by adding other open data files in the gui and plotting across multiple flent.gz files.

Thanks for the explanation. :)

**Comment by heistp** [comment]
So as it turns out, it would still be useful in this case to be able to plot the box plots for each flow in a tcp_nup test. Is there a way to do that?

**Comment by tohojo** [comment]
Pete Heist <notifications@github.com> writes:

> So as it turns out, it would still be useful in this case to be able
> to plot the box plots for each flow in a tcp_nup test. Is there a way
> to do that?

Sure, you just define a new plot definition with type=box instead of
type=box_combine :)
