### ISSUE TITLE
Restructuring the file format

### ISSUE THREAD

**Issue by tohojo** [tohojo/flent#20]
It would be good to restructure the file format a little bit. In no
particular order:

- Add a proper version field (yeah, should have done that from the start
guess).

- Move the raw data from SERIES_META into the top-level object, always
include it. Possibly even get rid of the aligned data and re-compute it
as needed?
    - Possibly restructure metadata so SERIES_META is somewhere
      else/different?

- Import data units into the series metadata.

- Use machine IDs (no spaces!) for the data series keys and convert them
to human-readable values on output (stored in the metadata, or in the
test config?).
    - This needs to (also) be an automatic mapping, so we can import old
    data files.

- Bzip instead of gzip?

Throughout all this, keep a compatibility layer so we can read old data
files (and convert them to the new format), but breaking compatibility
so old versions can't read the new files is fine.

**Comment by dtaht** [comment]
see the extensive discussion on the bloat mailing list.
