### ISSUE TITLE
marking parameter not working for tcp_1up test

### ISSUE THREAD

**Issue by heistp** [tohojo/flent#201]
I can set 'markings' for tcp_nup, but it seems that setting 'marking' on a tcp_1up test is not working. Any chance you could take a look or point me where to fix this?

**Comment by heistp** [comment]
Thanks! Works for me, only I got a little confused because 'tcp_cong_control' stopped working and is replaced by 'cc_algo'. It's no problem for me as I can adjust and it's more consistent now, just that people's existing batches may behave differently...

**Comment by tohojo** [comment]
Ugh, did I manage to mess that up? Will fix that, thanks for the head's up :)

**Comment by flent-users** [comment]
Toke Høiland-Jørgensen <notifications@github.com> writes:

> Ugh, did I manage to mess that up? Will fix that, thanks for the
> head's up :)

Fixed in 34ed66346fbb7b4c47e9df6650ce9bc5a4f99fe9
