### ISSUE TITLE
ss_iterate.sh yields corrupted output

### ISSUE THREAD

**Issue by oliviertilmans** [tohojo/flent#204]
I am running on a pretty-much bare host, where I have
```bash
$ ss -V
ss utility, iproute2-ss191125
```

It turns out that when `ss_iterate.sh` runs `ss -ntp [...]`, `ss` does not output a new line at the very end. This causes `ss_iterate.sh` to collate the output with the `Time` field, resulting in the socket stat records being all empty as the runner fails to parse a timestamp.

I resolved this locally by tweaking `ss_iterate.sh` to output a new line between w/e output ss prints, and the timestamp, i.e., I changed the command string generation to:

```diff
command_string=$(cat <<EOF
for i in \$(seq $count); do
    ss -t -i -p -n state connected "dst $target $filter"
+   echo ''
    date '+Time: %s.%N';
    echo "---";
    sleep $interval || exit 1;
done
EOF
)
```

I don't have the time to test whether this would have any impact on hosts where `ss` prints a proper ouput, hence why this is not a PR. An alternate way could be to put the timestamp generation _before_ the invocation of `ss`. In both cases, the only issue would be if the output was parsed without regex--which did not seem to be the case from a quick glance.

For reference, this is an example output from `ss_iterate.sh` without that hotfix:
```
State      Recv-Q       Send-Q            Local Address:Port            Peer Address:Port      Process                                                                                        
ESTAB      5882764      0                     127.0.0.1:5001               127.0.0.1:57192      users:(("iperf",pid=409625,fd=4))
         cubic wscale:7,7 rto:203.333 rtt:0.012/0.006 ato:40 mss:32768 pmtu:65535 rcvmss:65483 advmss:65483 cwnd:10 bytes_received:8207120107 segs_out:102998 segs_in:179272 data_segs_in:179270 send 218453333333bps lastsnd:1544 lastack:10 pacing_rate 436906666664bps delivered:1 rcv_rtt:0.033 rcv_space:4784075 rcv_ssthresh:3112347 minrtt:0.012Time: 1587807728.735334444
```
Note the unfortunate location of the timestamp.

**Comment by tohojo** [comment]
Olivier Tilmans <notifications@github.com> writes:

> I am running on a pretty-much bare host, where I have
> ```bash
> $ ss -V
> ss utility, iproute2-ss191125
> ```
>
> It turns out that when `ss_iterate.sh` runs `ss -ntp [...]`, `ss` does
> not output a new line at the very end. This causes `ss_iterate.sh` to
> collate the output with the `Time` field, resulting in the socket stat
> records being all empty as the runner fails to parse a timestamp.

Thank you for the report! I seems this was already fixed in iproute2 -
see commit:

9eee92a41ae6 ("ss: fix end-of-line printing in misc/ss.c")

This is dated Dec 4th, 2019, so I guess it's just after the version
you're running.

> I resolved this locally by tweaking `ss_iterate.sh` to output a new
> line between w/e output ss prints, and the timestamp, i.e., I changed
> the command string generation to:
>
> ```diff
> command_string=$(cat <<EOF
> for i in \$(seq $count); do
>     ss -t -i -p -n state connected "dst $target $filter"
> +   echo ''
>     date '+Time: %s.%N';
>     echo "---";
>     sleep $interval || exit 1;
> done
> EOF
> )
> ```
>
> I don't have the time to test whether this would have any impact on
> hosts where `ss` prints a proper ouput, hence why this is not a PR. An
> alternate way could be to put the timestamp generation _before_ the
> invocation of `ss`. In both cases, the only issue would be if the
> output was parsed without regex--which did not seem to be the case
> from a quick glance.

Yeah, the Flent parser for Ss output is entirely regex-based, so it just
needs the timestamp at the beginning of a line. So I'm fine with adding
your change as well :)

**Comment by dtaht** [comment]
I note if you are running into heisenbugs, patches exist for both tc and ss to let it poll on an interval. Much better than a script, not accepted upstream....

**Comment by dtaht** [comment]
I'd also really like this to work on osx.
/me hides

**Comment by tohojo** [comment]
On 26 April 2020 21:23:10 CEST, "Dave Täht" <notifications@github.com> wrote:
>I note if you are running into heisenbugs, patches exist for both tc
>and ss to let it poll on an interval. 

Exist where?
