### ISSUE TITLE
Status of "--enabled-demo" mode for macOS Homebrew installs of Netperf

### ISSUE THREAD

**Issue by kris-anderson** [tohojo/flent#207]
I have to start by saying this isn't your problem. But I'm also not sure on the status of this and from what I can tell you're the last person I can see that said anything about reaching out to the Netperf devs to enable this flag:

https://github.com/Homebrew/homebrew-core/pull/25503

Did you ever hear back from them? If not, is there anything I can do to help make this easier for macOS users?

The Homebrew dev did mention in your PR that we could create a tap for this. Is that something you would want to maintain? Would you like me to create a tap under my account and create a PR to update your README file to help macOS users get Flent up and running?

**Comment by kris-anderson** [comment]
Sounds good!

I put together a working [brew tap](https://github.com/kris-anderson/homebrew-netperf) that should solve this for others. I'll take a look at creating a PR for you in the next couple of days to update the README and hopefully make running Flent easy for all macOS users using Homebrew.

I tried to keep my tap true to the original formulae, so it still downloads the same original file from HP, but it does a find and replace during install to patch the file and then it adds the flag `--demo-mode` when compiling.

**Comment by tohojo** [comment]
Kris Anderson <notifications@github.com> writes:

> Sounds good!
>
> I put together a working [brew
> tap](https://github.com/kris-anderson/homebrew-netperf) that should
> solve this for others. I'll take a look at creating a PR for you in
> the next couple of days to update the README and hopefully make
> running Flent easy for all macOS users using Homebrew.
>
> I tried to keep my tap true to the original formulae, so it still
> downloads the same original file from HP, but it does a find and
> replace during install to patch the file and then it adds the flag
> `--demo-mode` when compiling.

LGTM, thanks!

**Comment by kris-anderson** [comment]
I want to think about the naming a bit more before I create a PR (undecided on `netperf-demo-mode` or if that should be something else like `netperf-enable-demo` or something). Do you have an opinion on the package name? Homebrew will use `netperf` by default, but they recommend using a new name to keep the installs a little simpler for end users.

I also refactored the readme a bit. Not sure if you're a fan of this look, but wanted to get your thoughts before I submit a PR. Here's my branch with the README changes this far:
https://github.com/kris-anderson/flent/tree/update-readme-for-macos

**Comment by tohojo** [comment]
Kris Anderson <notifications@github.com> writes:

> I want to think about the naming a bit more before I create a PR
> (undecided on `netperf-demo-mode` or if that should be something else
> like `netperf-enable-demo` or something). Do you have an opinion on
> the package name? Homebrew will use `netperf` by default, but they
> recommend using a new name to keep the installs a little simpler for
> end users.

Yeah, naming is the hardest part :)
I'm no better at it myself, so don't really have any opinion. Other than
the fact that I don't like the 'demo mode' feature name in the first
place - it has the wrong connotations, I think ("demo" sounds a bit too
much like "beta", or something unfinished).

> I also refactored the readme a bit. Not sure if you're a fan of this look, but wanted to get your thoughts before I submit a PR. Here's my branch with the README changes this far:
> https://github.com/kris-anderson/flent/tree/update-readme-for-macos

I think it's better to move 'other linux' up with debian/ubuntu/Arch,
but other than that, no objections :)
