### ISSUE TITLE
Is netperf.bufferbloat.net alive?

### ISSUE THREAD

**Issue by sebelk** [tohojo/flent#209]
Hi, sorry for the silly question, but I've run:

`flent rrul -p all_scaled -l 60 -H netperf.bufferbloat.net -t my-graph -o filename.png`

And get errors such as:

```
Stdout: establish control: are you sure there is a netserver listening on netperf.bufferbloat.net at port 12865?
establish_control could not establish the control connection from 0.0.0.0 port 0 address family AF_INET to netperf.bufferbloat.net port 12865 address family AF_INET
```

Is 12865 the correct port?

Thanks in advance!

**Comment by tohojo** [comment]
sebelk <notifications@github.com> writes:

> Hi, sorry for the silly question, but I've run:
>
> `flent rrul -p all_scaled -l 60 -H netperf.bufferbloat.net -t my-graph -o filename.png`
>
> And get errors such as:
>
> ```
> Stdout: establish control: are you sure there is a netserver listening on netperf.bufferbloat.net at port 12865?
> establish_control could not establish the control connection from 0.0.0.0 port 0 address family AF_INET to netperf.bufferbloat.net port 12865 address family AF_INET
> ```
>
> Is 12865 the correct port?
>
> Thanks in advance!

That server sometimes runs out of bandwidth (it's hosted by a volunteer
on a bandwidth-limited connection). So if it's down, it's down; you can
try one of the others (netperf-west.bufferbloat.net or
netperf-eu.bufferbloat.net)

**Comment by sebelk** [comment]
thanks :)
