### ISSUE TITLE
How to create two simultaneous tests using flent-gui?

### ISSUE THREAD

**Issue by lealog** [tohojo/flent#216]
Hi,

I'm trying to create two simultaneous tests using flent-gui but I'm always receiving the same error "RuntimeError: Found no hostnames on lookup of 192.168.56.103,192.168.56.102".

Using the CLI I'm able to run the tests using "udo flent rtt_fair_var_mixed -l 60 -H 192.168.56.102 -H 192.168.56.103 -t test_two_hosts_6".

Can you please clarify is this is supported by flent-gui?

**Comment by tohojo** [comment]
lealog <notifications@github.com> writes:

> Hi,
>
> I'm trying to create two simultaneous tests using flent-gui but I'm
> always receiving the same error "RuntimeError: Found no hostnames on
> lookup of 192.168.56.103,192.168.56.102".
>
> Using the CLI I'm able to run the tests using "udo flent
> rtt_fair_var_mixed -l 60 -H 192.168.56.102 -H 192.168.56.103 -t
> test_two_hosts_6".
>
> Can you please clarify is this is supported by flent-gui?

Hmm, no, it isn't, but let's fix that :)

**Comment by lealog** [comment]
Thanks :)
Are you planning to change the Flent version? I'm asking this because I want to test this "new" feature :)

**Comment by tohojo** [comment]
lealog <notifications@github.com> writes:

> Thanks :)
> Are you planning to change the Flent version? I'm asking this because
> I want to test this "new" feature :)

Yeah, a new release is way overdue. Will try to get around to it before
the holidays :)

**Comment by lealog** [comment]
Thanks :)
