### ISSUE TITLE
Flent in Docker?

### ISSUE THREAD

**Issue by richb-hanover** [tohojo/flent#220]
I read an intriguing article - [Run more stuff in Docker](https://jonathan.bergknoff.com/journal/run-more-stuff-in-docker/). It showed a solution to a big frustration: getting the right version of Flent, Python, netperf, and all the other libraries onto my computer without screwing up other software.

Is anyone working on a Dockerfile that bundles up Flent with its preferred support packages? This sounds like a good enhancement to the already enhanced 2.0 version. I don't have a lot of time, but might take it on in the next month to six weeks.

**Comment by tohojo** [comment]
Rich Brown <notifications@github.com> writes:

> I read an intriguing article - [Run more stuff in
> Docker](https://jonathan.bergknoff.com/journal/run-more-stuff-in-docker/).
> It showed a solution to a big frustration: getting the right version
> of Flent, Python, netperf, and all the other libraries onto my
> computer without screwing up other software.
>
> Is anyone working on a Dockerfile that bundles up Flent with its
> preferred support packages? This sounds like a good enhancement to the
> already enhanced 2.0 version. I don't have a lot of time, but might
> take it on in the next month to six weeks.

I'm not a huge fan of Docker, so no, no plans for this. If you want to
take a stab at it, go ahead. It does feel a bit overkill for something
as small as Flent, though. What exactly is your problem with getting
Flent to run today?

**Comment by richb-hanover** [comment]
>What exactly is your problem with getting Flent to run today? 

It's nothing specific to Flent. I install software sporadically. Whenever I do, I face the kinds of problems described in the article (old 2.7 version of Python, some silly version of Qt, etc.) I don't have a formal system for keeping versions under control. I know about nvm, pyenv, but don't keep them updated. (Oh, yes. and brew, as well...)

It's worse on macOS, because its system Python was (or at least formerly) was acknowledged to be *ancient.* I never really understood which one I was going to get. So...

* I'll treat this as an opportunity to horse around with Docker again.
* I have plenty to do, so if someone wants to snatch it out of my hands, feel free.

Thanks.

**Comment by tohojo** [comment]
xciter327 ***@***.***> writes:

> Here is what I setup for a quick n dirty testing. It's a pretty "fat"
> image, but I don't feel like optimizing it at this point. You can
> probably do away with a bunch of dependencies if You relegate yourself
> to cli only Flent. It was based on a previous attempt I saw somewhere
> here.

Thanks! I'd be happy to include this as an example in the repository
under packaging/ if you'd care to open a pull request for it? :)

**Comment by teohhanhui** [comment]
Came across https://github.com/cdeex/flent-docker while looking for a Docker image.
