### ISSUE TITLE
--remote-host doesn't seem to work correctly

### ISSUE THREAD

**Issue by bkiziuk** [tohojo/flent#222]
I'm trying to use flent for running traffic between different hosts (other than the one flent is running).
According to what I have read and understand, the following command: 
```
./run-flent --host 192.168.98.5 tcp_2up  --remote-host 0=iperf@192.168.98.42 --remote-host 1=iperf@192.168.98.44 --log-file=log.txt
```
executed on 192.168.98.43 should:
- connect via SSH to hosts 192.168.98.42 and 44
- fork the netperf to connect from above two hosts to 192.168.98.5

The actual result is that traffic is sent from 192.168.98.43 to 192.168.98.5. 192.168.98.42 and 44 do not record any traffic on their interfaces.
However, if I execute the command:
```
./run-flent --host 192.168.98.5 tcp_1up  --remote-host 0=iperf@192.168.98.42 --log-file=log.txt
```
the result is that 192.168.98.42 is sending 1Gbit/s of traffic, 192.168.98.43 is also sending 1Gbit/s traffic and 192.168.98.5 is receiving 1Gbit/s traffic - according to nload tools on every host.

Am I doing any mistake here? I'm using the current master branch.
[log.zip](https://github.com/tohojo/flent/files/6137109/log.zip)

**Comment by tohojo** [comment]
bkiziuk ***@***.***> writes:

> I'm trying to use flent for running traffic between different host.
> According to what I have read and understand, the following command: 
> ```
> ./run-flent --host 192.168.98.5 tcp_2up  --remote-host ***@***.*** --remote-host ***@***.*** --log-file=log.txt
> ```

The tcp_2up test has a ping flow, and two runners computing average and
totals. Those take up indexes 0, 1 and 2, so the actual TCP flows start
from 3. You can see this by running the test and looking at the metadata
(with `flent -f metadata mytestfile.flent.gz`) - look for the IDX value
in the objects in SERIES_META.

**Comment by bkiziuk** [comment]
Ok, I can see it now. Many thanks for valuable explanation :-)

**Comment by tohojo** [comment]
You're welcome! :)
