### ISSUE TITLE
Add Gentoo support to your home page.

### ISSUE THREAD

**Issue by garyemiller** [tohojo/flent#223]
Gentoo has an ebuild for flent: net-analyzer/flent

Please add to your home page with the other distros.

**Comment by tohojo** [comment]
"Gary E. Miller" ***@***.***> writes:

> Gentoo has an ebuild for flent: net-analyzer/flent
>
> Please add to your home page with the other distros.

Sure, absolutely! Thank you for the suggestion!

What's the command to install ebuilds on Gentoo these days? Just `emerge net-analyzer/flent` ?

**Comment by garyemiller** [comment]
> What's the command to install ebuilds on Gentoo these days? Just `emerge net-analyzer/flent` ?

Yes, that is the proper command:

```
emerge net-analyzer/flent
```

I know it works, I just did it.  Dave Taht recommended Flent to me.  So I'm checking it out.

**Comment by tohojo** [comment]
Awesome, thanks!
