### ISSUE TITLE
Restructure the settings handling

### ISSUE THREAD

**Issue by tohojo** [tohojo/flent#23]
Currently, the settings are stored in on big object with no module
namespacing. This object is then passed around everywhere, leading to
tight coupling, and making it difficult to see which parts of the code
use which settings.

Doing this differently, and having each module / class explicitly take
their needed parameters as call arguments should clear this up.

While we're at it, might as well upgrade the argument parsing code to
use the argparse module. Should be more flexible, _and_ we won't have to
do our own ini file parsing anymore.

Depends on #24 since argparse is Python 2.7+.

**Comment by tohojo** [comment]
Moving to argparse will also make it possible to automatically generate documentation: https://pythonhosted.org/sphinxcontrib-autoprogram/

There's a pypi argparse module for Python 2.6 we can depend on if needed.

**Comment by dtaht** [comment]
I don't know if this is a related bug or not, but enabling scale mode and then disabling it leads to not being able to later have data->add-other-data-files not working.

**Comment by tohojo** [comment]
That's definitely a separate bug. Please file as such...

**Comment by tohojo** [comment]
Fixed in 7741771a6ab1aef7e3c3530fd3080952887a1784
