### ISSUE TITLE
KeyError in parse_raw

### ISSUE THREAD

**Issue by hrishikeshathalye** [tohojo/flent#244]
parse_raw in class DitgRunner throws a KeyError when using DITG to generate VoIP traffic.

![Screenshot from 2021-11-01 16-57-18](https://user-images.githubusercontent.com/43074572/139679142-f3c2429e-e078-4f86-adde-57504af63b4f.png)

Printing the parts dictionary reveals the reason to be incorrect parsing of the DITG output.

![Screenshot from 2021-11-01 16-59-17](https://user-images.githubusercontent.com/43074572/139679657-f550152b-02c3-4653-8bef-5b2b01a75d9a.png)

Changing the regex `parts = re.split(r">?\s*", line)` to `parts = list(filter(None, re.split(r"(\S+)>\s*", line)))` can fix the issue.

Can submit a PR if needed.

**Comment by tohojo** [comment]
> Can submit a PR if needed.

Please do! :)
