### ISSUE TITLE
Value of Bpl used in calculation of MOS scores for VoIP

### ISSUE THREAD

**Issue by hrishikeshathalye** [tohojo/flent#247]
In the mos_score function in util.py the value of Bpl used in the calculation is 1. Whereas, in the G.107 recommendation, the default recommended value is 4.3 and the permitted range is from 4.3 to 40. MOS values for some combinations of delay and loss are calculated incorrectly due to this. Setting Bpl to 4.3 will make the code conform exactly to the reference implementation given here https://www.itu.int/ITU-T/studygroups/com12/emodel/calculnb.php

![Screenshot from 2022-01-10 21-06-36](https://user-images.githubusercontent.com/43074572/148793474-70d41b43-e7a2-423f-b202-7d6da4a90556.png)

**Comment by tohojo** [comment]
Hmm, interesting; thank you for the head's up! I guess the '1' value
comes from the code (which has '1' as the default also on that web
page). Feel free to open a pull request to fix this!

**Comment by hrishikeshathalye** [comment]
Another small change. Also changed equation (7-27) considering the value of sT as 1.
