### ISSUE TITLE
Unable to start flent-gui

### ISSUE THREAD

**Issue by huaracheguarache** [tohojo/flent#259]
I'm unable to start flent-gui on Fedora 35, and I get the following message in the terminal:

```
[michael@localhost ~]$ flent --gui
Starting Flent 2.0.1 using Python 3.10.2.
ERROR: Unable to find a usable Qt version.
```

I'm running the latest flent and netperf versions installed with dnf. My report is pretty sparse and I imagine you need more info to help me/figure out why this is happening, so please just ask.

**Comment by tohojo** [comment]
Michael Yartys ***@***.***> writes:

> I'm unable to start flent-gui on Fedora 35, and I get the following message in the terminal:
>
> ```
> ***@***.*** ~]$ flent --gui
> Starting Flent 2.0.1 using Python 3.10.2.
> ERROR: Unable to find a usable Qt version.
> ```
>
> I'm running the latest flent and netperf versions installed with dnf.
> My report is pretty sparse and I imagine you need more info to help
> me/figure out why this is happening, so please just ask.

`dnf install python3-QtPy python3-matplotlib` should get you sorted. The
'flent' package doesn't depend on these because they pull in quite a few
dependencies, and they're not needed to run tests...

**Comment by huaracheguarache** [comment]
Unfortunately, I still get the same error message after installing the packages you suggested (only python3-QtPy-1.11.2-1.fc35.noarch was missing).

**Comment by tohojo** [comment]
Michael Yartys ***@***.***> writes:

> Unfortunately, I still get the same error message after installing the
> packages you suggested (only python3-QtPy-1.11.2-1.fc35.noarch was
> missing).

Heh, seems the python3-QtPy packages doesn't actually depend on any of
the backends, so you'll need to manually install python3-pyside2 and
python3-matplotlib-qt5 as well...

**Comment by huaracheguarache** [comment]
Thanks! That solved the issue, but I've discovered a new one while trying to run a test (I'll open a new issue).
