### ISSUE TITLE
VoIP Tests Failing

### ISSUE THREAD

**Issue by hrishikeshathalye** [tohojo/flent#263]
I just pulled the latest code. 
There seems to be an issue with running VoIP tests which now fail with the below error. It was working fine in an earlier commit and I am unable to spot the error.
![image](https://user-images.githubusercontent.com/43074572/161487919-a5a0e45a-bfda-4ac3-ac7a-5bcc8fb572e9.png)

This is the log file - https://zerobin.net/?d6185a07dbe3b2c1#ThxErzdomGda2jJIdkYkr/6W31NYPhIU2K5pKYSZy1c=

**Comment by tohojo** [comment]
Hmm, seems that broke during the parser refactoring; could you please try that PR and see if it helps?

**Comment by hrishikeshathalye** [comment]
Yes it works now

**Comment by tohojo** [comment]
Great, thanks for testing, and for the report! :)
