### ISSUE TITLE
flent GUI always fails with "TypeError: setValue(self, int): argument 1 has unexpected type 'float'" when starting a test.

### ISSUE THREAD

**Issue by vochong** [tohojo/flent#267]
flent --gui
Starting Flent 2.0.1 using Python 3.10.4.
Initialised matplotlib v3.5.1 on numpy v1.21.5.
GUI loaded. Using Qt through pyqt5 v5.15.2.
Starting tcp_download test. Expected run time: 40 seconds.
Traceback (most recent call last):
  File "/home/python/Venv/lib/python3.10/site-packages/flent/gui.py", line 1034, in update_progress
    self.progressBar.setValue(100 * elapsed / self.total_time)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
Aborted (core dumped)

flent --version
Starting Flent 2.0.1 using Python 3.10.4.
Flent v2.0.1.
Running on Python 3.10.4 (main, May 14 2022, 05:21:19) [GCC 12.1.0].
Using matplotlib version 3.5.1 on numpy 1.21.5.
Using Qt: pyqt5 v5.15.2.

**Comment by vochong** [comment]
The git version has fixed the issue.  Thanks a lot!

**Comment by Joshfindit** [comment]
Req: push a new release to the usual places.

Today I did `pip3 install flent` and got the affected version `2.0.1`
(macOS if that's important)

**Comment by tohojo** [comment]
Josh ***@***.***> writes:

> Req: push a new release to the usual places.

Yeah, this was way overdue, sorry about that. Tagged and pushed v2.1.0
to pypi now...
