### ISSUE TITLE
autodetection  of fping on flent

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#271]
https://forum.openwrt.org/t/aql-and-the-ath10k-is-lovely/59002/648 - perhaps a test of localhost could be added to fping, and when it gets a nan, spew out a more helpful error message about disabling stealth mode on the osx firewall.

**Comment by tohojo** [comment]
Dave Täht ***@***.***> writes:

> https://forum.openwrt.org/t/aql-and-the-ath10k-is-lovely/59002/648 -
> perhaps a test of localhost could be added to fping, and when it gets
> a nan, spew out a more helpful error message about disabling stealth
> mode on the osx firewall.

Well, it's doing a test against localhost, and failing, in which case
Flent will refuse to use it. I guess we could add a second attempt to
ping something on the internet...
