### ISSUE TITLE
bug on debian testing

### ISSUE THREAD

**Issue by Mwaye** [tohojo/flent#272]
Hi,

I've got a problem to run flent 2.0.1 on my debian with python 3.10.
In another debian (stable with python 2.9 and flent 2.0.0) it work without issue.

The issue is that when I want to launch a test, the gui crash with a message like "error in gui.py" and it seems concerning the progression bar.
It works when open a file generated in a terminal by flent cli.

I don't find similar error in the issue list but sorry if my problem is always asked.
Did someone know what could be the panel and the solution ?

Thanks a lot.
Bests regards, 

Benjam

Sorry for my bad English

**Comment by tohojo** [comment]
I think you're hitting #261. I'll cut a new release and get it into Debian as soon as I'm back from vacation :)

**Comment by Mwaye** [comment]
Hi,

Thanks for your answer.
Effectively out the same problem, I'll don't see it when searching a solution.

Sorry for the double post :(

No problem, I'll wait the new release and use flent via my VM and-or via the git version until the new release come.

Good vacations :)
And thanks again.
