### ISSUE TITLE
Bug on Debian 11

### ISSUE THREAD

**Issue by BenjaMwaye** [tohojo/flent#274]
Hi,

I know there's a bug run Flent on Debian testing and test cannot be run .
(progress bar bug that crash the GUI)
Is-it planed to correct this ?

Thanks a lot for your help.
BenjaMwaye

**Comment by tohojo** [comment]
Version 2.1.1, which contains a fix for this bug, should be making its way into the Debian repositories... :)

**Comment by BenjaMwaye** [comment]
Hi
Thanks a lot for your answer and your time.
It's a great news.

Have a good day.
Best regards,
Benjam

3 nov. 2022 18:04:06 Toke Høiland-Jørgensen ***@***.***>:
