### ISSUE TITLE
Feature Request: Add CPU plot to tests

### ISSUE THREAD

**Issue by infused-kim** [tohojo/flent#275]
Hi,

First of all... thank you for creating such an amazing piece of software. It is really helpful.

One thing I am missing though is the ability to plot the CPU load of the router. You can get it by using the option `--te=cpu_stats_hosts=root@192.168.2.1`.

The results are added to the JSON, but currently there is no way to actually visualize the data.

As a workaround, until this is added to flent, it's possible to edit the test config and add the following to the `PLOTS` list:
```python
PLOTS = o([
    ('cpu',
     {'description': 'CPU plot',
      'type': 'timeseries',
      'legend_title': 'CPU Load',
      'axis_labels': ['CPU Load'],
      'series': [
                 {'data': glob('cpu_stats_*'),
                  'label': ''}
                ]}),

    ('download',
     {'description': 'Download bandwidth plot',
      'type': 'timeseries',
      'legend_title': 'TCP download',
      'series': [{'data': 'TCP download BE',
                  'label': 'BE'},
                 {'data': 'TCP download BK',
                  'label': 'BK'},
                 {'data': 'TCP download CS5',
                  'label': 'CS5'},
                 {'data': 'TCP download EF',
                  'label': 'EF'},
                 {'data': 'TCP download avg',
                  'label': 'Avg',
                  'smoothing': 10,

                  'color': 'black',
                  'linewidth': 2}]}),
[...]
```

And then run it with:
```shell
flent -i rrul-2022-10-19T093407.952309.flent -p cpu -o cpu-plot.png
```
This will output a plot like this:
![cpu-plot](https://user-images.githubusercontent.com/7404004/196729455-8d3bf78a-02d3-4d35-b4a4-f81ea2350b5c.png)

**Comment by tohojo** [comment]
That 'cpu' plot should already appear when you load a file with the cpu
stats included. Could you please share the data file where this doesn't
work? Also, how are you looking at the plots (GUI, command line plots, etc)?

**Comment by infused-kim** [comment]
I am using the command line and non of the plots in —list-plots showed a cpu option. 

Or did I miss it somewhere?

Unfortunately, I can’t run the gui as qt5 is not supported on apple silicon macs.

I’ll upload the Flent file tomorrow when I’m back at my computer.

**Comment by infused-kim** [comment]
Ok, I have figured it out... The following plots are available: `cpu `, `cpu_box `, `cpu_bar `, `cpu_box_combine `, `cpu_bar_combine`

Thank you @tohojo!

**Comment by tohojo** [comment]
Cool! You're welcome! :)

**Comment by dtaht** [comment]
Please post plots of your work to the world. We really care that we get feedback like yours... and care more, when flent turns out useful for something. The comparison plot features are to die for.
