### ISSUE TITLE
ModuleNotFoundError: No module named 'matplotlib'

### ISSUE THREAD

**Issue by b-fett** [tohojo/flent#277]
was installed through aur repository

```bash
-> flent-gui 
Starting Flent 2.1.1 using Python 3.10.8.
Traceback (most recent call last):
  File "/usr/bin/flent-gui", line 33, in <module>
    sys.exit(load_entry_point('flent==2.1.1', 'gui_scripts', 'flent-gui')())
  File "/usr/lib/python3.10/site-packages/flent/__init__.py", line 88, in run_flent_gui
    return run_flent(gui=True)
  File "/usr/lib/python3.10/site-packages/flent/__init__.py", line 56, in run_flent
    from flent.gui import run_gui
  File "/usr/lib/python3.10/site-packages/flent/gui.py", line 49, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
```

**Comment by tohojo** [comment]
b-fett ***@***.***> writes:

> was installed through aur repository
>
> ```bash
> -> flent-gui 
> Starting Flent 2.1.1 using Python 3.10.8.
> Traceback (most recent call last):
>   File "/usr/bin/flent-gui", line 33, in <module>
>     sys.exit(load_entry_point('flent==2.1.1', 'gui_scripts', 'flent-gui')())
>   File "/usr/lib/python3.10/site-packages/flent/__init__.py", line 88, in run_flent_gui
>     return run_flent(gui=True)
>   File "/usr/lib/python3.10/site-packages/flent/__init__.py", line 56, in run_flent
>     from flent.gui import run_gui
>   File "/usr/lib/python3.10/site-packages/flent/gui.py", line 49, in <module>
>     import matplotlib
> ModuleNotFoundError: No module named 'matplotlib'
> ```

You'll need to install matplotlib to use the GUI (the package is called
`python-matplotlib` on Arch). I guess we could emit a better error
message in this case, though, will fix that...
