### ISSUE TITLE
Output of the plots

### ISSUE THREAD

**Issue by saslu** [tohojo/flent#285]
![image](https://github.com/tohojo/flent/assets/138210040/9a90cc91-8ad3-4475-9a22-988745ef7b99)
in this plot, download graph(the green graph) end few seconds before the ping graph(the orange graph) and also there is difference in the starting of both the graphs. Can anyone suggest me the command to solve this issue?

**Comment by tohojo** [comment]
So the ping is actually supposed to start five seconds before the download. What's the exact invocation of Flent you used to run this test?

**Comment by saslu** [comment]
I have used the tcp_8down benchmark for this test.

**Comment by tohojo** [comment]
saslu ***@***.***> writes:

> I have used the tcp_8down benchmark for this test.

Right, but I was after the exact command line you used (with all options
etc) :)

**Comment by saslu** [comment]
sudo flent tcp_8down -p totals --bounds-x 180 --zero-y --no-title -l 120 -H x.x.x.x -t Testing_29062023 -o Test_en_290623_${CC}_20ms_8down_Prague_trial.png

**Comment by tohojo** [comment]
saslu ***@***.***> writes:

> sudo flent tcp_8down -p totals --bounds-x 180 --zero-y --no-title -l 120 -H x.x.x.x -t Testing_29062023 -o Test_en_290623_${CC}_20ms_8down_Prague_trial.png

Hmm, okay, nothing totally obvious there. Could you please try to run it
with debug logging enabled (--log-file debug.log) and attach the log
file as well?

**Comment by saslu** [comment]
![image](https://github.com/tohojo/flent/assets/138210040/7c4e6ce8-c182-4011-bcff-df7873f80cc1)
I ran the debug file and this is the screenshot of it.

**Comment by saslu** [comment]
[debug.log](https://github.com/tohojo/flent/files/12001105/debug.log)

**Comment by tohojo** [comment]
Hmm, so looking at the timestamps in the debug log, it looks like they are correct and that the ping starts before the download. So does the graph look the same with that data file? I.e., was it a one-off occurrence for a single test run, or is it consistent?

**Comment by dtaht** [comment]
@saslu is this still an issue?
