### ISSUE TITLE
Run Flent with iperf

### ISSUE THREAD

**Issue by zanearniel** [tohojo/flent#306]
Im new to this tool. Can u please tell the steps to generate latency and throughput plots using flent with iperf?or Is there a way to feed the iperf output to flent to generate latency and throughput plots?

**Comment by tohojo** [comment]
zanearniel ***@***.***> writes:

> Im new to this tool. Can u please tell the steps to generate latency
> and throughput plots using flent with iperf?

Iperf if not generally supported. The only test that supports iperf is
the UDP bandwidth test, all the others require netperf.

**Comment by zanearniel** [comment]
> Iperf if not generally supported. The only test that supports iperf is
> the UDP bandwidth test, all the others require netperf.
 Oh ok.Thanks.
Im trying to see if I can send a fixed volume of data with flent test. Is there any way to have some control over rate of packet transmission?Like is there any other tool which can work on top of flent to control the data rate?Is it even possible??ur thoughts please

**Comment by tohojo** [comment]
zanearniel ***@***.***> writes:

>> Iperf if not generally supported. The only test that supports iperf is
>> the UDP bandwidth test, all the others require netperf.
>  Oh ok.Thanks.
>
> Im trying to see if I can send a fixed volume of data with flent test.
> Is there any way to have some control over rate of packet
> transmission?Like is there any other tool which can work on top of
> flent to control the data rate?Is it even possible??ur thoughts please

Netperf does support sending a fixed amount of data, so it would be
possible to implement support for this. Could you describe your use case
in a bit more detail, please? Why is it you need to send a fixed amount
of data, exactly? :)

-Toke

**Comment by zanearniel** [comment]
> Netperf does support sending a fixed amount of data, so it would be
> possible to implement support for this. Could you describe your use case
> in a bit more detail, please? Why is it you need to send a fixed amount
> of data, exactly? :)

Thanks for the reply! The issue is Im trying to evaluate the performance of dualpi2 qdisc. So im using rrul test to see the difference in performance but the issue is every time I run the test they packets generated are not the same always.Since I run multiple tests, I need to make sure that the amount of packets generated are the same for all the consecutive tests.Is it possible? :)

**Comment by tohojo** [comment]
zanearniel ***@***.***> writes:

>> Netperf does support sending a fixed amount of data, so it would be
>> possible to implement support for this. Could you describe your use case
>> in a bit more detail, please? Why is it you need to send a fixed amount
>> of data, exactly? :)
>
> Thanks for the reply! The issue is Im trying to evaluate the
> performance of dualpi2 qdisc. So im using rrul test to see the
> difference in performance but the issue is every time I run the test
> they packets generated are not the same always.Since I run multiple
> tests, I need to make sure that the amount of packets generated are
> the same for all the consecutive tests.

Why does the number of packets need to be the same for each test?

> Is it possible? :)

Not currently, but it would be possible to add such a feature to Flent.
I don't really have the time to work on this, though, so you'd have to
do some hacking yourself :)

**Comment by zanearniel** [comment]
> Why does the number of packets need to be the same for each test?

For benchmarking purposes.

> Not currently, but it would be possible to add such a feature to Flent.
> I don't really have the time to work on this, though, so you'd have to
> do some hacking yourself :)

Thanks for your time.I will try it out :)
Closing the issue for now!
