### ISSUE TITLE
Crash during startup on ubuntu 24.10

### ISSUE THREAD

**Issue by ajoe** [tohojo/flent#310]
Hi, 
Ubuntu 24.10 came out just today. I tried to install flent with: sudo apt install flent     
but got this errors during install: 
#################
flent (2.1.1-3) wird eingerichtet ...
/usr/share/flent/flent/metadata.py:247: SyntaxWarning: invalid escape sequence '\d'
  m = re.search("(qlen|txqueuelen) (\d+)", output)
/usr/share/flent/flent/metadata.py:259: SyntaxWarning: invalid escape sequence '\w'
  m = re.search("Duplex: (\w+)", output)
#################
But this install was completet. 
Then when I run "flent" I get this error in the Ubuntu error report tool:
#################
run crashed with ModuleNotFoundError in /usr/share/flent/flent/plotters.py: No module named 'distutils'
#################

Can anyone help? Will flent 2.2 solve this issue?
Thanks,
Jochen

**Comment by tohojo** [comment]
Yeah, please try v2.2.0 - you can install it from the ppa: https://launchpad.net/~tohojo/+archive/ubuntu/flent

**Comment by ajoe** [comment]
thanks, that solved it. So Ubuntu 24.10 needs flent v2.2.0. This steps solved it: 
sudo add-apt-repository ppa:tohojo/flent
sudo apt update

**Comment by ajoe** [comment]
solved
