### ISSUE TITLE
Being able to test multiple hosts, no matter how many flows

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#36]
If the HOSTS variable was a closure, where every reference to it became HOST = HOSTS[X = X + 1 % NUMBER_OF_HOSTS], it would be simpler to add more different RTTs to the mix and expand out to the huge numbers of flows I am attempting to look at.

Similarly, more robust handling/plotting of multiple flows would be nice.

**Comment by tohojo** [comment]
Not entirely sure I know what you mean here. Could you give an example
of what you want to be able to write?

As far as plotting more flows simultaneously, ideas welcome! :)

**Comment by dtaht** [comment]
What I would like to setup are servers throughout the world, and a default list of such embedded in flent. norway.servers.flent.org, redwoodcity.servers.flent.org, etc... these servers would have the more advanced tools (http and ditg) setup already...

as for the "closure" the "X" is would be a private variable to referencing each host... on tests that mandated something like --rotate-servers

**Comment by tohojo** [comment]
> What I would like to setup are servers throughout the world, and a default list
> of such embedded in flent. norway.servers.flent.org,
> redwoodcity.servers.flent.org, etc... these servers would have the more advanced
> tools (http and ditg) setup already...

Yes, but what has that got to do with the test specification language?

> as for the "closure" the "X" is would be a private variable to referencing each
> host... on tests that mandated something like --rotate-servers

This does not compute...
