### ISSUE TITLE
Fails to install correctly ubuntu 14.04

### ISSUE THREAD

**Issue by kdarbyshirebryant** [tohojo/flent#38]
after installing flent package 'flent' produces 'command not found', 'flent-gui' does work.

/usr/bin/flent points to ../share/flent/flent which is actually a directory
/usr/bin/flent-gui points to ../share/flent/flent-gui which does exist.

I suspect that 'flent' should live in ../share/flent but has instead been moved into that directory because it's called the same this as the directory.

**Comment by tohojo** [comment]
Ah yes, that's a name clash between the package name and binary. Bugger.

Hmm, will have to figure out what the proper way to fix this is...

**Comment by kdarbyshirebryant** [comment]
Yay! :-)
