### ISSUE TITLE
Mac OSX ping uses -t, not -w

### ISSUE THREAD

**Issue by alfs** [tohojo/flent#45]
The rrul-test produces an error on Mac OSX since the -w option is unknown and should use -t instead.

```
Data series: Ping (ms) ICMP
Runner: PingRunner
Command: /sbin/ping -n -D -i 0.20 -w 70   tptest.carl.kau.se
Standard error output:
  /sbin/ping: illegal option -- w
  usage: ping [-AaDdfnoQqRrv] [-b boundif] [-c count] [-G sweepmaxsize]
              [-g sweepminsize] [-h sweepincrsize] [-i wait] [−k trafficclass]
              [-l preload] [-M mask | time] [-m ttl] [-p pattern]
              [-S src_addr] [-s packetsize] [-t timeout][-W waittime] [-z tos]
              host
```

**Comment by tohojo** [comment]
Does OSX ping have a 'timestamp output' option (-D on Linux)?

Last time I checked it didn't; which unfortunately means that it can't
be used (since the timestamps are needed to relate the output data to
the other tools).

**Comment by dtaht** [comment]
I would mandate fping on osx and be done with it.

**Comment by alfs** [comment]
OSX ping has a -D flag, but it sets the Don't Fragment bit. (i.e. different option semantics that I mentioned at your presentation yesterday).
I did not find an option to enable timestamping output, so I agree with dthat, fping should (must) be used.

**Comment by tohojo** [comment]
Right, I'll add a check and complain loudly :)

**Comment by tohojo** [comment]
Could you check if the fix I just checked in correctly complains on OSX, please?
