### ISSUE TITLE
qdisc_stats test does not parse cake 

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#48]
in case this gets mangled: http://snapon.lab.bufferbloat.net/~d/cake.out

These are the three (thus far) known modes of "cake"

qdisc cake 8002: root refcnt 2 unlimited diffserv4 flows raw 
 Sent 1672 bytes 6 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0 
           Class 0     Class 1     Class 2     Class 3  
  rate          0bit        0bit        0bit        0bit
  target       5.0ms       5.0ms       5.0ms       5.0ms
interval     105.0ms     105.0ms     105.0ms     105.0ms
Pk delay         0us         0us         0us         0us
Av delay         0us         0us         0us         0us
Sp delay         0us         0us         0us         0us
  pkts             0           2           0           4
way inds           0           0           0           0
way miss           0           2           0           1
way cols           0           0           0           0
  bytes            0        1200           0         472
  drops            0           0           0           0
  marks            0           0           0           0
qdisc cake 8002: root refcnt 2 unlimited diffserv8 flows raw 
 Sent 3302 bytes 12 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0 
           Class 0     Class 1     Class 2     Class 3     Class 4     Class 5     Class 6     Class 7  
  rate          0bit        0bit        0bit        0bit        0bit        0bit        0bit        0bit
  target       5.0ms       5.0ms       5.0ms       5.0ms       5.0ms       5.0ms       5.0ms       5.0ms
interval     105.0ms     105.0ms     105.0ms     105.0ms     105.0ms     105.0ms     105.0ms     105.0ms
Pk delay         0us         0us         0us         0us         0us         0us         0us         0us
Av delay         0us         0us         0us         0us         0us         0us         0us         0us
Sp delay         0us         0us         0us         0us         0us         0us         0us         0us
  pkts             0           4           0           8           0           0           0           0
way inds           0           0           0           0           0           0           0           0
way miss           0           2           0           1           0           0           0           0
way cols           0           0           0           0           0           0           0           0
  bytes            0        2400           0         902           0           0           0           0
  drops            0           0           0           0           0           0           0           0
  marks            0           0           0           0           0           0           0           0
qdisc cake 8002: root refcnt 2 unlimited besteffort flows raw 
 Sent 3732 bytes 16 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0 
           Class 0  
  rate          0bit
  target       5.0ms
interval     105.0ms
Pk delay         0us
Av delay         0us
Sp delay         0us
  pkts             2
way inds           0
way miss           1
way cols           0
  bytes          228
  drops            0
  marks            0

**Comment by tohojo** [comment]
Right. Will have to think about how to store that... Don't think storing it as a two-dimensional data structure will work...

**Comment by tohojo** [comment]
Also, indent to preserve formatting...
