### ISSUE TITLE
collecting better wifi stats

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#49]
in the ath9k at least, there are several other useful sorts of stats that can be collected.

/sys/kernel/debug/ieee80211/phy0/netdev:sw00/stations/b8:3e:59:1a:00:63/rc_stats#
                                                     */netdev:*/stations/*/rc_stats

is one of them. The hard part to parse is what channels are being selected and why. There is a new version of this code in the latest minstrel-blues and minstrel-variance output that is rc_stats_csv and should be easier to parse.

/sys/kernel/debug/ieee80211/phy0/ath9k/xmit
                                             /phy*/
is the other. TX-Pkgts-All, TX-Bytes-All compared against aggregates and mpdus in their various forms for the queues available is good.

**Comment by tohojo** [comment]
So is this a once per test thing, or an over time thing?

**Comment by dtaht** [comment]
over time, just as you are polling tc now.
