### ISSUE TITLE
does remote-metadata not capture qdisc stats?

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#51]
mikaels dataset had no queue stats in it.

**Comment by tohojo** [comment]
It tries. However, it requires the right binaries to be available, and
in the PATH.

My guess is that for the dataset in question, tc and ip were missing -
openwrt doesn't install them by default...

**Comment by tohojo** [comment]
Or rather, probably 'ip' was missing. Flent uses that to get the IP and
route information to know which interface to pull the tc stats from.
