### ISSUE TITLE
Recv socket size / Send socket size 

### ISSUE THREAD

**Issue by alokhan** [tohojo/flent#53]
Hi,

Would it be possible to get these data in the metadata of test ? I am willing to add it by myself but I don't know where you parse the output of netperf.

Thanks

**Comment by tohojo** [comment]
The netperf output is self is parsed in NetperfDemoRunner.parse() in parsers.py.

If you want to capture the send buffer output, you'll also have to change the netperf invocation in testenv.py to not suppress those values.

Pull request very welcome :)
