### ISSUE TITLE
flent-gui not launching

### ISSUE THREAD

**Issue by cklatsky** [tohojo/flent#57]
Hi,

I believe I have installed all the needed packages for flent.  When I launch flent-gui, I get this error

Traceback (most recent call last):
  File "/usr/bin/flent-gui", line 11, in <module>
    sys.exit(run_flent_gui())
  File "/usr/lib/python2.6/site-packages/flent/__init__.py", line 81, in run_flent_gui
    return run_flent(gui=True)
  File "/usr/lib/python2.6/site-packages/flent/__init__.py", line 44, in run_flent
    return run_gui(settings)
  File "/usr/lib/python2.6/site-packages/flent/gui.py", line 68, in run_gui
    mainwindow = MainWindow(settings)
  File "/usr/lib/python2.6/site-packages/flent/gui.py", line 140, in __init__
    self.actionOpen.activated.connect(self.on_open)
AttributeError: 'QAction' object has no attribute 'activated'

Flent v0.11.1.
Running on Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)].
Using matplotlib version 0.99.1.1 on numpy 1.4.1.
Using PyQt4 version 4.6.2

**Comment by tohojo** [comment]
Yup, that was a bug when running with qt compiled without qt3 support. Already fixed; please try upgrading up Flent 0.13.0 and see if that works better :)

**Comment by cklatsky** [comment]
I was able to upgrade to Flent 0.13.0 using pip, but after the upgrade I cannot launch flent as it keeps telling me I need Python version 2.7.3 or later.  I have Python 2.7.6 install, but not in /usr/bin/python.  Its in /usr/local/bin/python.  This is so I can keep Python 2.6.6 on this Centos 6.4 box.  Any ideas on how I can configure Flent to use the Python 2.7.6 that is installed on this box?

[cklats000@klatsky01 Python-2.7.6]$ which python2.7
/usr/local/bin/python2.7

[cklats000@klatsky01 Python-2.7.6]$ python2.7
Python 2.7.6 (default, Nov 15 2015, 20:46:46)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>

[cklats000@klatsky01 Python-2.7.6]$ yum info python
Loaded plugins: fastestmirror, refresh-packagekit, security
Loading mirror speeds from cached hostfile
 * base: mirrors.rit.edu
 * centosplus: mirrors.rit.edu
 * contrib: mirrors.rit.edu
 * extras: mirrors.rit.edu
 * rpmforge: mirror.us.leaseweb.net
 * rpmforge-extras: mirror.us.leaseweb.net
 * rpmforge-testing: mirror.us.leaseweb.net
 * updates: mirrors.rit.edu
Installed Packages
Name        : python
Arch        : x86_64
Version     : 2.6.6
Release     : 64.el6
Size        : 78 k
Repo        : installed
From repo   : base
Summary     : An interpreted, interactive, object-oriented programming language
URL         : http://www.python.org/
License     : Python
Description : Python is an interpreted, interactive, object-oriented programming
            : language often compared to Tcl, Perl, Scheme or Java. Python includes
            : modules, classes, exceptions, very high level dynamic data types and
            : dynamic typing. Python supports interfaces to many system calls and
            : libraries, as well as to various windowing systems (X11, Motif, Tk,
            : Mac and MFC).
            :
            : Programmers can write new built-in modules for Python in C or C++.
            : Python can be used as an extension language for applications that need
            : a programmable interface.
            :
            : Note that documentation for Python is provided in the python-docs
            : package.
            :
            : This package provides the "python" executable; most of the actual
            : implementation is within the "python-libs" package.

[cklats000@klatsky01 Python-2.7.6]$

**Comment by tohojo** [comment]
cklatsky <notifications@github.com> writes:

> I was able to upgrade to Flent 0.13.0 using pip, but after the upgrade I cannot
> launch flent as it keeps telling me I need Python version 2.7.3 or later. I have
> Python 2.7.6 install, but not in /usr/bin/python. Its in /usr/local/bin/python.
> This is so I can keep Python 2.6.6 on this Centos 6.4 box. Any ideas on how I
> can configure Flent to use the Python 2.7.6 that is installed on this
> box?

Hmm, you can edit the flent binaries to use the right python; just point
the shebang path (the path following the #! on the first line) at
/usr/local/bin/python and you should be good to go.

The pip install should do this automatically, but that requires pip
itself to be run through the right python version.

-Toke

**Comment by cklatsky** [comment]
I change the shebang path for both flent & flent-gui to point to the python2.7 location, now I get a different error:

[cklats000@klatsky01 bin]$ flent
Traceback (most recent call last):
  File "/usr/bin/flent", line 7, in <module>
    from flent import run_flent
ImportError: No module named flent

[cklats000@klatsky01 bin]$ flent-gui
Traceback (most recent call last):
  File "/usr/bin/flent-gui", line 7, in <module>
    from flent import run_flent_gui
ImportError: No module named flent

[cklats000@klatsky01 bin]$ more flent
#!/usr/local/bin/python2.7

# -*- coding: utf-8 -*-
import re
import sys

from flent import run_flent

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(run_flent())
[cklats000@klatsky01 bin]$ more flent-gui
#!/usr/local/bin/python2.7

# -*- coding: utf-8 -*-
import re
import sys

from flent import run_flent_gui

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(run_flent_gui())

[cklats000@klatsky01 bin]$ pip show flent
---
Metadata-Version: 2.0
Name: flent
Version: 0.13.0
Summary: The FLExible Network Tester
Home-page: http://flent.org
Author: Toke HÃ¸iland-JÃ¸rgensen <toke@toke.dk>
Author-email: toke@toke.dk
License: GNU GPLv3
Location: /usr/lib/python2.6/site-packages
Requires:

**Comment by tohojo** [comment]
cklatsky <notifications@github.com> writes:

> I change the shebang path for both flent & flent-gui to point to the python2.7
> location, now I get a different error:

Ah, right. Well, you do need to install it with the right pip binary,
then... Do you have a pip in /usr/local/bin? If so do /usr/local/bin/pip
install flent. If not, you need to get yourself one :)

-Toke

**Comment by cklatsky** [comment]
Toke,

I went in a different direction and turned up a different VM that had Python 2.7.6, and I was able to get flent & flent-gui running.  I am closing this issue.

Thanks,
Carl
