### ISSUE TITLE
Testing additional streams in rrul_be, tcp_download, & tcp_upload tests?

### ISSUE THREAD

**Issue by cklatsky** [tohojo/flent#59]
Hi,

For the rrul_be, tcp_download, & tcp_upload tests, is there a way to increase the number of streams used in the test?  On our resource limited client platform, we would like to increase the rrul_be tests of 4 stream, and the tcp_down / up tests of 1 stream.

Thanks,
Carl

**Comment by tohojo** [comment]
cklatsky <notifications@github.com> writes:

> For the rrul_be, tcp_download, & tcp_upload tests, is there a way to
> increase the number of streams used in the test? On our resource
> limited client platform, we would like to increase the rrul_be tests
> of 4 stream, and the tcp_down / up tests of 1 stream

Yes, by using different tests. Have a look at the output of `flent
--list-tests`. For instance, the rrul_50up test will start 50 upload
streams and 1 download stream.

You can customise a bit by swapping the meaning of 'up' and 'down' by
the --swap-up-down parameter to Flent.

If you want more customisation options, you can create a new test
config. In that case, feel free to send a pull request with the new test
and I'll be happy to look it over and include it with the Flent sources :)

-Toke

**Comment by cklatsky** [comment]
Thanks Toke.  We tried rrul_50_down and that moves us in the direction we want, but probably with less streams.  For our new test config, we would like to work with 12 streams (rrul_be 12 up / 12 down, tcp_down with 12, tcp_up with 12).  Should each of those be entered under their own pull request, or just one pull request?

Also, as feature enhancement along this same approach, if there were global command line options to specify the number of streams on the command line with the test command, that would be really nice.  Should I enter that separately as a feature request?

Thanks,
Carl

**Comment by tohojo** [comment]
cklatsky <notifications@github.com> writes:

> Thanks Toke. We tried rrul_50_down and that moves us in the direction
> we want, but probably with less streams. For our new test config, we
> would like to work with 12 streams (rrul_be 12 up / 12 down, tcp_down
> with 12, tcp_up with 12). Should each of those be entered under their
> own pull request, or just one pull request?

Either is fine with me.

> Also, as feature enhancement along this same approach, if there were
> global command line options to specify the number of streams on the
> command line with the test command, that would be really nice. Should
> I enter that separately as a feature request?

Well, it would be possible to do, say, an 'rrul_var' test where you
could specify the actual number of streams via the test_parameters
functionality. Don't think there's any changes in Flent needed other
than writing a suitable test specification.

Feel free to try it out and submit it as a new test; otherwise I'll have
a look when I get around to it.

-Toke

**Comment by cklatsky** [comment]
Hi Toke,

I have upgraded flent to v13.0, but in the output of the --list-tests, I do not see an 'rrul_var' as an included test.

I am also unclear on the meaning of 'write a suitable test specification'.  My understanding of how flent works is to include the test name such as 'rrul_be' or 'tcp_download' on the command line with the other flent options.  And that the test was an unchangeble test in what it is doing.  Such as rrul_be is 4 streams up & 4 streams down with no changing that.  Can you please clarify the meaning of 'write a suitable test specification'?

Thanks,
Carl

**Comment by cklatsky** [comment]
Hi again,

I looked over the format of rrul_be.conf and rrul_50_down and think I understand what to modify for 12 & 12 down.  I have a local copy of the file I am editing and hopefully it will work.  Will let you know.

Regards,
Carl

**Comment by cklatsky** [comment]
Hi Toke,

As noted in my last comment, I was able to understand the *.conf test file format and have created my additional tests as needed for several different increments of up & down stream numbers.  I have one separate question which I will open under a new issue, and just close this issue now.

Thanks for all your help on this.

Regards,
Carl

**Comment by tohojo** [comment]
Cool. If you'd care to share your tests I'll be happy to include them into Flent. Pull requests welcome! :)

**Comment by cklatsky** [comment]
Hi Toke,

Sure, I'd be happy to share back the tests I made.  I made several tests for rrul_X_up_Y_down; tcp_Xdown; tcpX_up.  For the ping check, I followed the methodology of each of their parent tests where the new rrul tests create as many ping streams as there were downstream checks.  For tcp_Xdown and tcp_Xup, only one ping stream is included like tcp_download & tcp_upload.

Did you want me to create one pull request for each new test; or submit all the tests under one pull request?

Regards,
Carl

**Comment by tohojo** [comment]
Awesome, thanks! A single pull request is fine, but I'd prefer if that had each test as a separate commit :)

**Comment by cklatsky** [comment]
Sure.  If have done a github pull request, but this seems as good a time as any to learn.  For the 'base' and 'compare', which branches should I select for those?

**Comment by tohojo** [comment]
Hmm, the obvious ones. If I remember correctly that would be the matter branch in my repository as base and whatever branch you have your additional commits in as the other one...

**Comment by cklatsky** [comment]
I created the first pull request with a few of the new test files that I would like to submit.  I put them in one pull request but could not find a separate commit to individually commit the files.  I created the pull request against base multiplot to master.

Please confirm if this is correct as I have more test configurations to submit and want to ensure I am doing this correctly.

**Comment by tohojo** [comment]
cklatsky <notifications@github.com> writes:

> I created the first pull request with a few of the new test files that
> I would like to submit. I put them in one pull request but could not
> find a separate commit to individually commit the files. I created the
> pull request against base multiplot to master.
>
> Please confirm if this is correct as I have more test configurations
> to submit and want to ensure I am doing this correctly.

No, there's definitely something that went wrong there. To create a pull
request, what you want to do, basically:

1. Create your own fork of the repository on Github (the Fork button at
   the top).
2. Clone that fork to your local machine.
3. Add the tests to that local clone in the right place, and commit them
   to git with appropriate commit messages. This is where the "one
   commit per new test" comes in.
4. Push your changes to your own repository on github.
5. From your own repository, create a pull request. When doing so you
   will see the difference between the upstream master branch and your
   own branch, which should only contain the new commit(s) you created.

-Toke

**Comment by cklatsky** [comment]
Thanks Toke, that clears things up for me.  I will try those steps when I get into the office tomorrow.

**Comment by cklatsky** [comment]
OK, I followed all of the steps.  Each new test was entered with its own commit into the local clone, synced to the remote fork on github, then one pull request created from that fork to your master tohojo/flent.  Hopefully I did this correctly.

The earlier pull request that I entered on 2/5 can be rejected / closed.

Regards,
Carl

**Comment by cklatsky** [comment]
With your help, the new files were loaded.  The original issue in this ticket has been addressed, and we can continue the remainder of the discussion under pull request #61.  Closing this ticket now.
