### ISSUE TITLE
Way to set number of streams to number of cores

### ISSUE THREAD

**Issue by smalleni** [tohojo/flent#63]
Is there a way to launch flent with tcp upload/download with the number of streams defaulting to the number of cores?

**Comment by tohojo** [comment]
Sai Sindhur Malleni <notifications@github.com> writes:

> Is there a way to launch flent with tcp upload/download with the number of
> streams defaulting to the number of cores?

Not currently (other than shell scripts), but should be straight-forward
to add. Actually pinning the netperf instances to their own separate
cores is another matter, though...

-Toke
