### ISSUE TITLE
Graph features on high dpi displays are tiny

### ISSUE THREAD

**Issue by smithbone** [tohojo/flent#68]
I have a laptop with a new high dpi 3200x1800 display and flent graph features are hard to read because everything is so tiny.

Setting figure.dpi in my /etc/matplotlibrc file doesn't seem to make any difference.  

I see a  --figure-dpi=FIG_DPI in the --help but it says only for raster format files and setting that also does not make any difference.

**Comment by tohojo** [comment]
Are you using the Flent GUI, or are you plotting from the command line?

In any case high-DPI support seems to be somewhat lacking in matplotlib for the time being, so not sure there's much I can do about it. And when it does get fixed there's a chance the GUI will need to be ported to Qt5 to take advantage of it...

**Comment by smithbone** [comment]
I'm using the command line.

Setting figure.dpi in /etc/matplotlibrc works fine for my other matplotlib programs but not for flent.  Somehow flent is either overriding the figure.dpi setting or not allowing the system /etc/matplotlibrc to get loaded.

**Comment by tohojo** [comment]
Ah, right, it seems that the rc-file loading logic will actually reset
everything to default that is not specified in the config distributed
with Flent. That's no good...

-Toke

**Comment by smithbone** [comment]
This fix breaks for me:

Fatal error: Error loading PlotFormatter: TypeError("rc_params_from_file() got an unexpected keyword argument 'use_default_template'",).

**Comment by smithbone** [comment]
Here's my setup:

rsmith@gatito:~/projects/bloat$ flent -V
Flent v0.14.0-git-7d5b6e8.
Running on Python 3.4.3 (default, Oct 14 2015, 20:28:29)  [GCC 4.8.4].
Using matplotlib version 1.3.1 on numpy 1.8.2.
Using PyQt4 version 4.10.4

**Comment by tohojo** [comment]
Ah, damn, old matplotlib strikes again. Will see what I can do about that...

**Comment by tohojo** [comment]
Could you check if it has been fixed properly now? :)

**Comment by smithbone** [comment]
Yep.  Works now.  

Although, I am getting a message I don't remember seeing before:

rsmith@gatito:~/projects/bloat$ flent -p totals rrul rrul-2016-06-30T134018.912215.flent.gz 
/usr/lib/python3/dist-packages/matplotlib/scale.py:90: RuntimeWarning: invalid value encountered in less_equal
  mask = a <= 0.0

**Comment by tohojo** [comment]
Awesome! The other warning depends on the data; if there's a data point missing somewhere, some of the filtering will produce that message. Since it's fairly benign, I haven't gone to the trouble of silencing it... :)
