### ISSUE TITLE
longer filenames would help

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#69]
I don't know if you've got something close to the maximum sized filename or not, but as my test parameters have got longer, encoding them all into the filename has got harder.

touch asdfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
touch: cannot touch 'asdfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff': File name too long

**Comment by tohojo** [comment]
Dave Täht <notifications@github.com> writes:

> I don't know if you've got something close to the maximum sized filename or not, but as my test parameters have got longer,
> encoding them all into the filename has got harder.
>
> touch
> asdfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
>
> touch: cannot touch
> 'asdfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff':
> File name too long

Seems most file systems agree that 255 characters is the max:
https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits

Suppose there's no harm in increasing it, then :)

-Toke
