### ISSUE TITLE
Packet Size

### ISSUE THREAD

**Issue by smalleni** [tohojo/flent#71]
More of a question than an issue. Did not find any other platform to ask so hence filing an issue.
What is the default packet size used? Can it be changed?

**Comment by tohojo** [comment]
Sai Sindhur Malleni <notifications@github.com> writes:

> More of a question than an issue. Did not find any other platform to
> ask so hence filing an issue. What is the default packet size used?
> Can it be changed?

Do you mean for UDP or TCP tests?

Most tests are TCP based, so whatever max packet size the TCP
implementation supports.

For the few UDP tests it uses whatever iperf's default is (which seems
to be the max size that fits in an MTU).

-Toke
