### ISSUE TITLE
Please consider maintaining this software in Debian

### ISSUE THREAD

**Issue by irl** [tohojo/flent#74]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=831578

I'm currently packaging this for Debian, but your packaging work is actually not bad at all.

I'm happy if you would like to be the maintainer in Debian and I'll review and sponsor uploads for you.

**Comment by tohojo** [comment]
Iain Learmonth <notifications@github.com> writes:

> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=831578
>
> I'm currently packaging this for Debian, but your packaging work is
> actually not bad at all.
>
> I'm happy if you would like to be the maintainer in Debian and I'll
> review and sponsor uploads for you.

Thanks! I'd be delighted. Actually tried getting Flent into Debian once
before, but failed. What do I need to do?

Also, I take it from the other issue you opened that it would be OK to
package it as a Python 3 application? Been contemplating dropping Python
2 support for a while, but supporting (old versions of) Debian has been
an important reason not to...

-Toke

**Comment by irl** [comment]
You reply too quickly. I have a lot to get through this weekend, but I'll come back next week. For now, you can sign up to alioth.debian.org and let me know your username. I'll give you permissions to use the Debian git repo for flent. You'll then need to read about how to build packages (if you haven't already) using the git-buildpackage workflow.

You may find that you want to drop the debian directory from the upstream source (this repo) to keep things simpler.

For future updates to the package, you'll make the changes and push to git on alioth.debian.org, and also build a package and upload it to mentors.debian.net. From there I would review and upload.

If you're familiar with IRC, we can schedule a meeting time to go through this.

**Comment by irl** [comment]
(and yes, I was thinking we'd do Python 3, so this can be the first update you do)

**Comment by irl** [comment]
Your test suite doesn't seem to be passing within the minimal build environment, so it's perhaps best if we go through this together from the start. Let me know if you'd be available an evening next week for an IRC meeting to get a first revision uploaded to Debian unstable.

**Comment by tohojo** [comment]
Iain Learmonth <notifications@github.com> writes:

> You reply too quickly. I have a lot to get through this weekend, but
> I'll come back next week.

That's fine, I have a deadline of my own next week.

> For now, you can sign up to alioth.debian.org and let me know your
> username. I'll give you permissions to use the Debian git repo for
> flent. You'll then need to read about how to build packages (if you
> haven't already) using the git-buildpackage workflow.

Signed up as tohojo-guest. Will get back to this after by deadline,
probably around the end of next week. And yeah, we can do IRC. Evening
what time zone, though? I'm in CEST...

-Toke

**Comment by irl** [comment]
Ok cool. I'm UTC.

University of Aberdeen, working on MAMI project (in case you've heard of it). Other guys in the lab on NEAT project and we used to work on RITE (all EU funded).

**Comment by tohojo** [comment]
Iain Learmonth <notifications@github.com> writes:

> Ok cool. I'm UTC.
>
> University of Aberdeen, working on MAMI project (in case you've heard
> of it). Other guys in the lab on NEAT project and we used to work on
> RITE (all EU funded).

Ah, right. I'm at Karlstad University; I do believe we have people in
both NEAT and RITE (though I'm in any of them not myself). Not sure
about MAMI; that doesn't ring a bell. I've done some IETF work and have
run into Gorry Fairhurst, whom I believe is in your department?

-Toke

**Comment by tohojo** [comment]
So would sometime Sunday work for you for an IRC meeting? :)

**Comment by irl** [comment]
Sunday sounds good, afternoon is probably better for me.

**Comment by tohojo** [comment]
Iain Learmonth <notifications@github.com> writes:

> Sunday sounds good, afternoon is probably better for me.

15:00 CEST? Where?

-Toke

**Comment by irl** [comment]
Seems like a good time.

I am `irl` on Freenode and OFTC. Freenode is currently under DDoS, so just whichever one is not under DDoS will be fine.
