### ISSUE TITLE
New flent files not getting picked up by pip install --upgrade flent

### ISSUE THREAD

**Issue by cklatsky** [tohojo/flent#75]
Hi Toke,

I see some new test files like "tcp_4up_squarewave.conf" and other flent files have been posted.  I am trying to use pip to pick up the new files, but pip keeps reporting flent is up to date.

C:\Python27\Scripts>pip install --upgrade flent
Requirement already up-to-date: flent in c:\python27\lib\site-packages

Does anything need to change on the Git repo to flag new changes for flent are available?

I am running this on Windows.

Regards,
Carl

**Comment by tohojo** [comment]
cklatsky <notifications@github.com> writes:

> Hi Toke,
>
> I see some new test files like "tcp_4up_squarewave.conf" and other flent files have been posted. I am trying to use pip to pick up the
> new files, but pip keeps reporting flent is up to date.
>
> C:\Python27\Scripts>pip install --upgrade flent
> Requirement already up-to-date: flent in c:\python27\lib\site-packages
>
> Does anything need to change on the Git repo to flag new changes for
> flent are available?

The pip installer doesn't pull from git, but from the release version,
which is from February. A new release is way overdue, but I've been hung
up on a deadline for other stuff (which is today).

I'll try to get a new release out sometime next week. In the meantime
you'll have to use the git version. You can install the git version by
cloning the git repository and issuing 'python setup.py install' from
within the cloned directory - that should work on Windows as well :)

-Toke

**Comment by cklatsky** [comment]
OK, thanks Toke.  That alternate upgrade method worked.
