### ISSUE TITLE
Measure overhead of latency measurement flows

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#78]
when you are regularly reducing latencies by orders of magnitude, sometimes you want to check to see if you are really winning or not. so, and not have any measurement flows.

--suppress-ping --suppress-udp --suppress-load

would be better than testname_noping as we do today.

**Comment by tohojo** [comment]
There's a (fairly new) --filter-series option that will filter out things when plotting. Is that good enough, or do you want to change the tests?

**Comment by dtaht** [comment]
wanted to be able to disable some segment of a test while testing, to
get a better "feel" for life without measurement flows.

**Comment by tohojo** [comment]
Hmm, not sure that's a good idea. It would change the meaning of the test name... What's the problem with just having a different test?

**Comment by tohojo** [comment]
I think the right thing here is to measure the overhead of the measurement flows instead of suppressing them.

**Comment by dtaht** [comment]
measuring this would be helpful

**Comment by tohojo** [comment]
Dave Täht <notifications@github.com> writes:

> measuring this would be helpful

Any reason you can't just use irtt, in which case it is negligible?

**Comment by dtaht** [comment]
I didn't realize irtt had grown so feature complete! --hmac! lovely!
