### ISSUE TITLE
clicking on File->run-new test is "interesting"

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#83]
GUI loaded. Running on PyQt v4.11.4.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flent-1.0.0_git_525c8e6-py2.7.egg/flent/gui.py", line 819, in run_test
    dialog = NewTestDialog(self, self.settings, self.log_queue)
  File "/usr/local/lib/python2.7/dist-packages/flent-1.0.0_git_525c8e6-py2.7.egg/flent/gui.py", line 832, in __init__
    tests = ListTests.get_tests(settings)
  File "/usr/local/lib/python2.7/dist-packages/flent-1.0.0_git_525c8e6-py2.7.egg/flent/settings.py", line 110, in get_tests
    settings.load_test(t, informational=True)
  File "/usr/local/lib/python2.7/dist-packages/flent-1.0.0_git_525c8e6-py2.7.egg/flent/settings.py", line 563, in load_test
    s = test_env.execute(filename)
  File "/usr/local/lib/python2.7/dist-packages/flent-1.0.0_git_525c8e6-py2.7.egg/flent/testenv.py", line 100, in execute
    "Unable to read test config file '%s': '%s'." % (filename, e))
RuntimeError: Unable to read test config file '/usr/local/lib/python2.7/dist-packages/flent-1.0.0_git_525c8e6-py2.7.egg/flent/tests/tcp_4up_square.conf': 'invalid syntax (tcp_4up_square.conf, line 33)'.

**Comment by tohojo** [comment]
Is it possible that 'tcp_4up_square.conf' is a test file you added
yourself and that is broken? :)

-Toke

**Comment by dtaht** [comment]
Oh, no, I'd *never* do something like that. OK, well. I did. nuked it. I have not used the run tests option before. Still borked in a different way.

Here's what happened when trying the burst test, and a few other tests.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flent-1.0.0_git_525c8e6-py2.7.egg/flent/gui.py", line 891, in run_test
    self.settings.load_test(informational=True)
  File "/usr/local/lib/python2.7/dist-packages/flent-1.0.0_git_525c8e6-py2.7.egg/flent/settings.py", line 562, in load_test
    filename = os.path.join(TEST_PATH, self.NAME + ".conf")
TypeError: unsupported operand type(s) for +: 'QVariant' and 'unicode'

**Comment by dtaht** [comment]
this appears to be a python 2.7 error trying it in 3.0 gives me:

GUI loaded. Running on PyQt v4.11.4.
Starting bursts test. Expected run time: 60 seconds.
flent-gui: Fatal IO error: client killed

Did you intend to ship this feature this time?

**Comment by tohojo** [comment]
Sure, the feature has been there for ages. But it wasn't until the addition of the logging stuff that it became really useful...

**Comment by dtaht** [comment]
flent      flent-gui  
d@dancer:~/git/flent$ flent-gui 
WARNING: Falling back to Qt4 for the GUI. Please consider installing PyQt5.

GUI loaded. Running on PyQt v4.11.4.
ERROR: Unable to read test config file '/usr/local/lib/python3.5/dist-packages/flent-1.0.0_git_c92add2-py3.5.egg/flent/tests/tcp_4up_square.conf': 'invalid syntax (tcp_4up_square.conf, line 33)'.

Now bypassed.

But:

Starting bursts test. Expected run time: 60 seconds.
flent-gui: Fatal IO error: client killed

**Comment by dtaht** [comment]
So... specifying multiple hosts for a test that wants them doesn't work. and the test completes but shows no output. 

![ruiningtokesday](https://cloud.githubusercontent.com/assets/108682/21958676/babf73d2-da68-11e6-8db8-8556e2a47904.png)

d@dancer:~/lede$ ps aux | grep netperf
d        11306  0.0  0.0  18192  2312 pts/44   S+   14:47   0:00 /usr/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y CS0 CS0 -H snapon.lab.bufferbloat.net -t TCP_STREAM -l 60 -f m -- -H snapon.lab.bufferbloat.net
d        11308  0.0  0.0  18192  2176 pts/44   S+   14:47   0:00 /usr/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y CS0 CS0 -H snapon.lab.bufferbloat.net -t TCP_MAERTS -l 60 -f m -- -H snapon.lab.bufferbloat.net
d        11310  0.0  0.0  18192  2176 pts/44   S+   14:47   0:00 /usr/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y CS1 CS1 -H snapon.lab.bufferbloat.net -t TCP_STREAM -l 60 -f m -- -H snapon.lab.bufferbloat.net
d        11320  0.0  0.0  18192  2328 pts/44   S+   14:47   0:00 /usr/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y CS1 CS1 -H snapon.lab.bufferbloat.net -t TCP_MAERTS -l 60 -f m -- -H snapon.lab.bufferbloat.net

**Comment by tohojo** [comment]
That looks like it's "just" netperf hanging. No watchdog timers.

And no, you can't specify multiple hosts.

As for the other error, try running flent-gui with --debug-error and see if it outputs any backtraces. What's the flent --version output?

**Comment by dtaht** [comment]
Hmm. flent-freemont.bufferbloat.net was alive earlier.... (I just enabled dnssec... hmmm)

d@dancer:~/git/flent$ flent-gui Summary of bursts test run 'bla' (at 2017-01-14 23:32:08.925191):

                             avg       median      # data pts
 Ping (ms) ICMP   :        81.73        81.50 ms          301
 Ping (ms) UDP BE :        81.50        81.30 ms          299
 Ping (ms) UDP BK :        81.50        81.33 ms          299
 Ping (ms) UDP EF :        81.30        81.08 ms          299
 Ping (ms) avg    :        81.43        81.33 ms          301



WARNING: Falling back to Qt4 for the GUI. Please consider installing PyQt5.



GUI loaded. Running on PyQt v4.11.4.
ERROR: Unable to read test config file '/usr/local/lib/python3.5/dist-packages/flent-1.0.0_git_0b7325d-py3.5.egg/flent/tests/tcp_4up_square.conf': 'invalid syntax (tcp_4up_square.conf, line 33)'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flent-1.0.0_git_0b7325d-py3.5.egg/flent/settings.py", line 623, in lookup_hosts
    hostname = util.lookup_host(h)
  File "/usr/local/lib/python3.5/dist-packages/flent-1.0.0_git_0b7325d-py3.5.egg/flent/util.py", line 195, in lookup_host
    socket.SOCK_STREAM)
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flent-1.0.0_git_0b7325d-py3.5.egg/flent/gui.py", line 912, in run_test
    self.pid = b.fork_and_run(self.log_queue)
  File "/usr/local/lib/python3.5/dist-packages/flent-1.0.0_git_0b7325d-py3.5.egg/flent/batch.py", line 548, in fork_and_run
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/flent-1.0.0_git_0b7325d-py3.5.egg/flent/batch.py", line 592, in run
    return self.run_test(self.settings, self.settings.DATA_DIR, True)
  File "/usr/local/lib/python3.5/dist-packages/flent-1.0.0_git_0b7325d-py3.5.egg/flent/batch.py", line 485, in run_test
    settings.load_test()
  File "/usr/local/lib/python3.5/dist-packages/flent-1.0.0_git_0b7325d-py3.5.egg/flent/settings.py", line 579, in load_test
    self.lookup_hosts()
  File "/usr/local/lib/python3.5/dist-packages/flent-1.0.0_git_0b7325d-py3.5.egg/flent/settings.py", line 628, in lookup_hosts
    % (h, e))
RuntimeError: Hostname lookup failed for host flent-freemont.bufferbloat.net: [Errno -5] No address associated with hostname
flent-gui: Fatal IO error: client killed
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python3: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.

**Comment by tohojo** [comment]
I renamed it to 'fremont' - that's what the city is called :)

**Comment by dtaht** [comment]
Well, as a test of the thing not crashing when handed an incorrect dns thing, that last commit worked nice to capture the log and not crash. It gathers the log... and then hangs so thoroughly that you have to hit the X on the window to get it to go away.

(an abort test button?) 

it also seems to be a modal window, in that - even if you succeed in a test - you can't go to the other window with the graph and gain keyboard control. (so you kill the run test window with the x on the main part of the window, and walla! First time I've ever seen this work... )

![cubic_reno_cake](https://cloud.githubusercontent.com/assets/108682/21959129/c36114b4-da72-11e6-9a95-a381afb87788.png)

**Comment by dtaht** [comment]
And when repeating a test (after killing it with X), it ends up going to the end of the test name list (wlan-retries) instead of retaining prior values.

**Comment by tohojo** [comment]
Right, so I think that most of the obvious issues with the new test dialog are now fixed; it should be possible to abort tests, the dialog is no longer modal, and the logging settings are now propagated from the main window.

If you can confirm that things work now, I'll do a 1.0.1 release with these bug fixes :)
