### ISSUE TITLE
we should retire snapon as a default target

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#84]
925.71 Mbits/s         301
 TCP upload BE2 snapon.lab.bufferbloat.net                        : No data.
 TCP upload BK1 demo.tohojo.dk          

I'd point at: flent-freemont.bufferbloat.net flent-eu.bufferbloat.net flent-newark.bufferbloat.net flent-london.bufferbloat.net perhaps?

except I don't know the flent-eu address. I have one in germany.....

**Comment by tohojo** [comment]
They used to be called netperf-*.bufferbloat.net - and isn't that supposed to be 'fremont'?
