### ISSUE TITLE
qdisc_stats might be broken

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#87]
I may have forgot the correct syntax, but see the metadata in:

http://www.taht.net/~d/tcstats/

The command line I used was:

flent-gui --te=qdisc_stats_hosts=root@172.26.16.1 --te=qdisc_stats_interfaces=eth0

tc_iterate is on the router.

Also the comon.inc include is missing from most tests.

**Comment by tohojo** [comment]
Debug log?

**Comment by dtaht** [comment]
doesn't parse or recognise cake

 Ping (ms) ICMP flent-dallas.bufferbloat.net    :        53.17        53.08 ms              651
 Ping (ms) ICMP flent-fremont.bufferbloat.net   :        17.70        17.50 ms              651
 Ping (ms) ICMP flent-london.bufferbloat.net    :       157.94       157.71 ms              650
 Ping (ms) ICMP flent-newark.bufferbloat.net    :        91.92        91.84 ms              651
 Ping (ms) ICMP flent-tokyo.bufferbloat.net     :       118.12       118.00 ms              651
 Ping (ms) avg                                  :        88.10        88.13 ms              651
 TCP upload BE flent-atlanta.bufferbloat.net    :         0.80         0.81 Mbits/s         599
 TCP upload BE flent-dallas.bufferbloat.net     :         0.91         0.90 Mbits/s         599
 TCP upload BE flent-fremont.bufferbloat.net    :         1.08         1.06 Mbits/s         600
 TCP upload BE flent-london.bufferbloat.net     :         0.76         0.78 Mbits/s         596
 TCP upload BE flent-newark.bufferbloat.net     :         0.81         0.82 Mbits/s         598
 TCP upload BE flent-tokyo.bufferbloat.net      :         0.79         0.79 Mbits/s         598
 TCP upload avg                                 :         0.86         0.87 Mbits/s         602
 TCP upload fairness                            :         0.98         0.97 Idx             602
 TCP upload sum                                 :         5.15         5.21 Mbits/s         602
 qdisc_stats_root@172.26.16.1::backlog_bytes    :         0.00         0.00 bytes           648
 qdisc_stats_root@172.26.16.1::backlog_pkts     :         0.00         0.00 packets         648
 qdisc_stats_root@172.26.16.1::backlog_requeues :         0.00         0.00 packets         648
 qdisc_stats_root@172.26.16.1::dropped          :        -0.01         0.00 packets         648
 qdisc_stats_root@172.26.16.1::ecn_mark         : No data.
 qdisc_stats_root@172.26.16.1::overlimits       :       482.70         0.00 packets         648
 qdisc_stats_root@172.26.16.1::requeues         :         0.00         0.00 packets         648
 qdisc_stats_root@172.26.16.1::sent_bytes       :         2.34         2.34 Gbytes          648
 qdisc_stats_root@172.26.16.1::sent_pkts        :   1746387.26   1743117.45 packets         648
 qdisc_stats_root@172.26.64.1::backlog_bytes    :         0.00         0.00 bytes           648
 qdisc_stats_root@172.26.64.1::backlog_pkts     :         0.00         0.00 packets         648
 qdisc_stats_root@172.26.64.1::backlog_requeues :         0.00         0.00 packets         648
 qdisc_stats_root@172.26.64.1::dropped          :         0.00         0.00 packets         648
 qdisc_stats_root@172.26.64.1::ecn_mark         :         0.00         0.00 packets         648
 qdisc_stats_root@172.26.64.1::overlimits       :       734.97       734.00 packets         648
 qdisc_stats_root@172.26.64.1::requeues         :         0.00         0.00 packets         648
 qdisc_stats_root@172.26.64.1::sent_bytes       :        42.60        42.54 Mbytes          649
 qdisc_stats_root@172.26.64.1::sent_pkts        :    284407.04    284036.00 packets         649

**Comment by tohojo** [comment]
Please run with -L and post the resulting debug log...

**Comment by dtaht** [comment]
http://www.taht.net/~d/cakeparse.log has the log
http://www.taht.net/~d/cakeparse.flent.gz 
The script?

#!/bin/sh

# Yet another quick and dirty shell script to abuse a network

F=4
H=`hostname`
D=.bufferbloat.net
T="debug-$H-Flows=$F-single-cake-dual-srchost-dual-dsthost"
SITES="fremont dallas tokyo newark london atlanta"
S="-L /tmp/cakeparse.log -l 120 --te=qdisc_stats_hosts=root@172.26.16.1,root@172.26.64.1 --te=qdisc_stats_interfaces=eth0,eth0"

for i in `seq 1 $F`
do
for d in $SITES
do
S="$S -H flent-${d}$D"
done
done

flent -6 -t ipv6-$T $S rtt_fair_var_up
exit 0

**Comment by tohojo** [comment]
Dave Täht <notifications@github.com> writes:

> http://www.taht.net/~d/cakeparse.log has the log

Ah. Seems the parser gets confused by the ingress qdisc stats...

-Toke

**Comment by dtaht** [comment]
Nope. Doesn't parse ecn marks, drops or backlog for cake.

**Comment by tohojo** [comment]
Does 'make test' succeed on your box?

**Comment by tohojo** [comment]
As far as I can tell, the parsing is working correctly now. Are you sure the reason you're not seeing any ECN marks is not because there aren't any? In your log file, a lot of the output showed 0 marks.

Otherwise, please post another data file and corresponding log file.

Also, there was a bug in the C tools running on the router. Pushed updated packages to the LEDE repos for that.

**Comment by dtaht** [comment]
I will get on this friday.

**Comment by dtaht** [comment]
I meant, *this* friday.

**Comment by tohojo** [comment]
I assume this is fixed? If not, feel free to reopen.
