### ISSUE TITLE
figuring out what you are pointing at.

### ISSUE THREAD

**Issue by jgettys** [tohojo/flent#89]
It is great that pointing at a line in a graph highlights it.

It would be wonderful if it also highlighted the key information for that line....

**Comment by tohojo** [comment]
Yes. I seem to recall trying to get it to do that and failing at some point...

**Comment by chromi** [comment]
Heck, just displaying the coordinates of the pointer would be helpful.

**Comment by tohojo** [comment]
chromi <notifications@github.com> writes:

> Heck, just displaying the coordinates of the pointer would be helpful.

matplotlib already does this, in the lower right corner. Only issue is
that on dual-axis graphs, only one of the axis' coords is displayed...

-Toke
