### ISSUE TITLE
Give Flent Plots a little more whitespace at top and bottom

### ISSUE THREAD

**Issue by richb-hanover** [tohojo/flent#92]
Flent plots (see, for example, http://www.taht.net/~d/worldwide_fairness.png) tend not to have any pixels of whitespace on the top or bottom.

This looks bad: it seems harder to recognize the letterform's shape when the black edge of the image touches the letter. For example, the bar of the T's in "RTT" touch the top of the image, and the descenders of "Length/step" are cut off. I feel as if I have to squint at the words to read them.

This could be solved by adding pixels of whitespace at the top and bottom, or drawing the legends a few pixels lower/higher. I would recommend that the number of pixels be at least half of the "cap height" (height of a capital letter). Thanks.

**Comment by dtaht** [comment]
I agree with this. Also I wouldn't mind if it cropped the left and right whitespace to half a char also. 

Additionally, support for the Comic Sans font is a MUST!

**Comment by tohojo** [comment]
Dave Täht <notifications@github.com> writes:

> I agree with this. Also I wouldn't mind if it cropped the left and
> right whitespace to half a char also.

Well, the 0-border images are good for embedding in a document (where
the surrounding background is white). Could probably add configurable
whitespace, though...

> Additionally, support for the Comic Sans font is a MUST!

You can change the matplotlib fonts in
~/.config/matplotlib/matplotlibrc; Flent will pick that up :)

-Toke

**Comment by richb-hanover** [comment]
>Well, the 0-border images are good for embedding in a document (where
the surrounding background is white). 

Yes, but... Images in documents are easily cropped if necessary, while the lack of whitespace makes the everyday plots generated by Flent appear suboptimal.

> Could probably add configurable whitespace, though...

I don't think it's necessary: 

a) it's a bear to document ("--whitespace  Add a few pixels of whitespace to the top and bottom of the plot so that text doesn't touch the background"); 
b) no one will test it; 
c) I bet nobody will notice if the whitespace just appears in the next build.

**Comment by tohojo** [comment]
Well, except for the fact that I am one of the people who has a habit of putting Flent graphs into documents... ;)

I'll see if I can come up with a solution that works for both use cases...
