### ISSUE TITLE
PingRunner: ping command in uses locale-dependent decimal point

### ISSUE THREAD

**Issue by hnyman** [tohojo/flent#95]
I installed the newest flent version to my current buildhost (Ubuntu x64 16.10) and when I tried to run flent, I got an error for the "PingRunner" and the ICMP stats were left empty in the output.

I figured out that apparently the flent script commands use the US decimal points and that causes an error (with my Finnish locale that uses decimal comma: LC_NUMERIC=fi_FI.UTF-8 ).

Apparently it is enough to use env variable to set the local for the ping command:

Below is the console output with the original error, manual command
* failing with interval "0.20", 
* succeeding with interval "0.20" when env variable "LC_NUMERIC=en_US.utf8" is applied
* succeeding with interval "0,20"

Based on that, a simple solution might be to apply "LC_NUMERIC=en_US.utf8" to the ping command (or the whole flent???). Or somehow set the locale in "Python way".

It would be great if you can fix that in the main script.

(I looked up at the runners.py code and it looks like that also installing fping would bypass the problem due to milliseconds parameter. EDIT. that worked ok)

```
Started Flent 1.0.1 using Python 3.5.2+.
Starting rrul test. Expected run time: 160 seconds.
WARNING: Program exited non-zero.
Runner class: PingRunner
Command: /bin/ping -n -D -i 0.20 -w 160   netperf-eu.bufferbloat.net
Return code: 2
Stdout: 
Stderr: ping: bad timing interval
...

$ /bin/ping -n -D -i 0.20 -w 160   netperf-eu.bufferbloat.net
ping: bad timing interval

$ LC_NUMERIC=en_US.utf8 /bin/ping -n -D -i 0.20 -w 160   netperf-eu.bufferbloat.net
PING kau.toke.dk (130.243.26.64) 56(84) bytes of data.
[1487018429.067157] 64 bytes from 130.243.26.64: icmp_seq=1 ttl=52 time=17.3 ms
[1487018429.269049] 64 bytes from 130.243.26.64: icmp_seq=2 ttl=52 time=18.2 ms

$ /bin/ping -n -D -i 0,20 -w 160   netperf-eu.bufferbloat.net
PING kau.toke.dk (130.243.26.64) 56(84) bytes of data.
[1487018440.522989] 64 bytes from 130.243.26.64: icmp_seq=1 ttl=52 time=16.9 ms
[1487018440.724295] 64 bytes from 130.243.26.64: icmp_seq=2 ttl=52 time=17.6 ms
[1487018440.926407] 64 bytes from 130.243.26.64: icmp_seq=3 ttl=52 time=17.6 ms
```

**Comment by tohojo** [comment]
They change the decimal point for the command line parameter based on locale? That's ridiculous!

But yeah, can make Flent set locale to something sane... Which is probably just 'C'...
