### ISSUE TITLE
Issue loading file discussed on [Make-wifi-fast] mailing list

### ISSUE THREAD

**Issue by cklatsky** [tohojo/flent#98]
Hi Toke,

Following up on the issue we were discussing on the [Make-wifi-fast] mailing list, I was a having trouble loading a test file being provided by another user on the mailing list.  You had asked to try again and capture some debug logs.  I tried again using the -L log option and was able to capture a log file.  Launch commands & output noted below.  Log file and test results file attached.  When I loaded the file, the loading indicator just kept spinning.  I finally just hit X to close out the GUI.

-Carl

[testlog.txt](https://github.com/tohojo/flent/files/805077/testlog.txt)
[rrul_be-2017-01-27T180312.725940.cake_fd_eth_ap_10ms_35mbit.flent.gz](https://github.com/tohojo/flent/files/805078/rrul_be-2017-01-27T180312.725940.cake_fd_eth_ap_10ms_35mbit.flent.gz)

C:\Python27\Scripts>flent --gui --new-gui-instance -L testlog.txt
Started Flent 1.0.1-git using Python 2.7.11.
WARNING: Falling back to Qt4 for the GUI. Please consider installing PyQt5.

Initialised matplotlib v1.5.1 on numpy v1.11.0.
GUI loaded. Running on PyQt v4.11.4.
No handlers could be found for logger "flent.gui"
No handlers could be found for logger "flent.gui"
No handlers could be found for logger "flent.gui"
No handlers could be found for logger "flent.gui"
ERROR: Unable to load file 'C:\temp\bufferbloat\rrul_be-2017-01-27T180312.725940.cake_fd_eth_ap_10ms_35mbit.flent.gz': 'Unable to read inpu
\temp\bufferbloat\rrul_be-2017-01-27T180312.725940.cake_fd_eth_ap_10ms_35mbit.flent.gz''

---------From original mail discussion----------
> Finally had some time to get to this request. I downloaded the current 
> git version of Flent and was able to launch the flent-gui on Windows. 
> I had some old test *.flent.gz results files which loaded just fine. I 
> tried to open the test files that were linked from Pete Heist mail 
> "[Cake] Flent results for point-to-point Wi-Fi on LEDE/OM2P-HS 
> available". Those files did not load for some reason.
>
> Note, in Windows I am only using Flent to view results files in the 
> GUI. I do not use it to launch tests from Windows.

It would be helpful if you could turn on debug logging and exception debugging in the GUI, or run with -L logfile.txt from the command line, and post the resulting log entries (after trying to load the files that didn't work) somewhere... :)

-Toke

**Comment by tohojo** [comment]
cklatsky <notifications@github.com> writes:

> Hi Toke,
>
> Following up on the issue we were discussing on the [Make-wifi-fast]
> mailing list, I was a having trouble loading a test file being
> provided by another user on the mailing list. You had asked to try
> again and capture some debug logs. I tried again using the -L log
> option and was able to capture a log file. Launch commands & output
> noted below. Log file and test results file attached. When I loaded
> the file, the loading indicator just kept spinning. I finally just hit
> X to close out the GUI.

Hmm, it appears that that file is not actually gzipped. Maybe a web
server somewhere helpfully removed the compression somewhere along the
line?

If you rename the file to drop the .gz, or alternatively just recompress
it, I think it'll open :)

-Toke

**Comment by cklatsky** [comment]
OK, that was it.  By removing the .gz extension, the file was able to be loaded in properly.

The original request from you & Dave was to have someone try the latest Flent out on Windows.  Since I am only loading & reviewing generated test files on Flent / Windows and not actually launching any Flent / Netperf tests from Windows, I think this all I can check and we can close this issue.

**Comment by tohojo** [comment]
cklatsky <notifications@github.com> writes:

> OK, that was it. By removing the .gz extension, the file was able to be loaded in properly.
>
> The original request from you & Dave was to have someone try the
> latest Flent out on Windows. Since I am only loading & reviewing
> generated test files on Flent / Windows and not actually launching any
> Flent / Netperf tests from Windows, I think this all I can check and
> we can close this issue.

Awesome, thanks for testing! :)

-Toke
