### ISSUE TITLE
`--netperf-control-port` does not work

### ISSUE THREAD

**Issue by dixudx** [tohojo/flent#99]
When I try to specify a customized netperf server using `--netperf-control-port`, for example **12345** instead of the default **12865**, `netperf` will still use **12865**.

```sh
$ flent tcp_download --netperf-control-port=12345 -p totals -l 10 -H xx.xx.xx.xx -t text-to-be-included-in-plot -o download_speed.png
```

> Started Flent 1.0.1 using Python 2.7.5.
Starting tcp_download test. Expected run time: 20 seconds.
WARNING: Program exited non-zero.
Runner class: NetperfDemoRunner
Command: /usr/local/bin/netperf -P 0 -v 0 -D -0.20 -4  -H xx.xx.xx.xx -t TCP_MAERTS -l 10 -f m   --   -H xx.xx.xx.xx 
Return code: 255
Stdout: establish control: are you sure there is a netserver listening on xx.xx.xx.xx at port 12865?
establish_control could not establish the control connection from 0.0.0.0 port 0 address family AF_INET to xx.xx.xx.xx port 12865 address family AF_INET

> Stderr: 
WARNING: Command produced no valid data.
Runner class: NetperfDemoRunner
Command: /usr/local/bin/netperf -P 0 -v 0 -D -0.20 -4  -H xx.xx.xx.xx -t TCP_MAERTS -l 10 -f m   --   -H xx.xx.xx.xx 
Return code: 255
Stdout: establish control: are you sure there is a netserver listening on xx.xx.xx.xx at port 12865?
establish_control could not establish the control connection from 0.0.0.0 port 0 address family AF_INET to xx.xx.xx.xx port 12865 address family AF_INET

> Stderr: 
Data file written to ./tcp_download-2017-03-01T125739.353354.text_to_be_included_in_plot.flent.gz.
Initialised matplotlib v2.0.0 on numpy v1.12.0.

**Comment by tohojo** [comment]
Yeah, this was an oversight; already fixed in git (by fcc0c0a6322826d0dcd1175c325e54a63bd03e60).
